#!/usr/bin/env python

import sys

try:
   # Application is already installed
   import series60_remote.series60_remote as s60
except ImportError:
   # Application isn't installed
   import pc.series60_remote as s60

s60.Main()
