#!/bin/bash

#obexftp -b 00:1B:AF:84:FF:E2 -B 11 --chdir /E:/Python/ --mkdir libs
#sleep 1
obexftp -b 00:1B:AF:84:FF:E2 -B 11 --chdir /E:/Python/ --put ../mobile/mobile.py
sleep 1
obexftp -b 00:1B:AF:84:FF:E2 -B 11 --chdir /E:/Python/libs --put devices/status_numbers.py
