# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/contacts_edit.ui'
#
# Created: Wed Nov 17 12:05:57 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ContactsEdit(object):
    def setupUi(self, ContactsEdit):
        ContactsEdit.setObjectName("ContactsEdit")
        ContactsEdit.setWindowModality(QtCore.Qt.WindowModal)
        ContactsEdit.resize(852, 618)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/contacts"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContactsEdit.setWindowIcon(icon)
        ContactsEdit.setModal(True)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ContactsEdit)
        self.verticalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(ContactsEdit)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.generalTab)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(3, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.thumbButton = ImageButton(self.generalTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbButton.sizePolicy().hasHeightForWidth())
        self.thumbButton.setSizePolicy(sizePolicy)
        self.thumbButton.setText("")
        self.thumbButton.setObjectName("thumbButton")
        self.horizontalLayout_18.addWidget(self.thumbButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(3, 5, 5, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setContentsMargins(8, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.generalTab)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.name = QtGui.QLineEdit(self.generalTab)
        self.name.setEnabled(False)
        self.name.setText("")
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.horizontalLayout_13.addWidget(self.name)
        self.editNameButton = QtGui.QPushButton(self.generalTab)
        self.editNameButton.setObjectName("editNameButton")
        self.horizontalLayout_13.addWidget(self.editNameButton)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.nickname_label = QtGui.QLabel(self.generalTab)
        self.nickname_label.setText("Nickname:")
        self.nickname_label.setObjectName("nickname_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.nickname_label)
        self.nickname = QtGui.QLineEdit(self.generalTab)
        self.nickname.setObjectName("nickname")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.nickname)
        self.horizontalLayout_14.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.line = QtGui.QFrame(self.generalTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.jobLayout = QtGui.QFormLayout()
        self.jobLayout.setContentsMargins(3, 5, 5, 5)
        self.jobLayout.setObjectName("jobLayout")
        self.company_label = QtGui.QLabel(self.generalTab)
        self.company_label.setText("Company:")
        self.company_label.setObjectName("company_label")
        self.jobLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.company_label)
        self.company = QtGui.QLineEdit(self.generalTab)
        self.company.setObjectName("company")
        self.jobLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.company)
        self.jobtitle_label = QtGui.QLabel(self.generalTab)
        self.jobtitle_label.setText("Job title:")
        self.jobtitle_label.setObjectName("jobtitle_label")
        self.jobLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.jobtitle_label)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.jobtitle_1 = QtGui.QLineEdit(self.generalTab)
        self.jobtitle_1.setObjectName("jobtitle_1")
        self.horizontalLayout_15.addWidget(self.jobtitle_1)
        self.add_jobtitle = QtGui.QToolButton(self.generalTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/list-add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_jobtitle.setIcon(icon1)
        self.add_jobtitle.setObjectName("add_jobtitle")
        self.horizontalLayout_15.addWidget(self.add_jobtitle)
        self.jobLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.verticalLayout_2.addLayout(self.jobLayout)
        self.line_2 = QtGui.QFrame(self.generalTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtGui.QLabel(self.generalTab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.general_address = QtGui.QTextBrowser(self.generalTab)
        self.general_address.setEnabled(False)
        self.general_address.setObjectName("general_address")
        self.verticalLayout.addWidget(self.general_address)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.editGeneralAddressButton = QtGui.QPushButton(self.generalTab)
        self.editGeneralAddressButton.setObjectName("editGeneralAddressButton")
        self.horizontalLayout_16.addWidget(self.editGeneralAddressButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_3 = QtGui.QFrame(self.generalTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setContentsMargins(3, 5, 5, 5)
        self.formLayout_4.setObjectName("formLayout_4")
        self.birthday_label = QtGui.QLabel(self.generalTab)
        self.birthday_label.setText("Birthday:")
        self.birthday_label.setObjectName("birthday_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.birthday_label)
        self.birthday = QtGui.QDateEdit(self.generalTab)
        self.birthday.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.birthday.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.birthday.setCalendarPopup(True)
        self.birthday.setObjectName("birthday")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.birthday)
        self.label_7 = QtGui.QLabel(self.generalTab)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groups = QtGui.QLineEdit(self.generalTab)
        self.groups.setEnabled(False)
        self.groups.setObjectName("groups")
        self.horizontalLayout_17.addWidget(self.groups)
        self.editGroupsButton = QtGui.QPushButton(self.generalTab)
        self.editGroupsButton.setObjectName("editGroupsButton")
        self.horizontalLayout_17.addWidget(self.editGroupsButton)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.horizontalLayout_29.addLayout(self.verticalLayout_2)
        self.line_4 = QtGui.QFrame(self.generalTab)
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_29.addWidget(self.line_4)
        self.scrollArea = QtGui.QScrollArea(self.generalTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 537))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.generalNumbersLayout = QtGui.QFormLayout()
        self.generalNumbersLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.generalNumbersLayout.setContentsMargins(5, 5, 3, 5)
        self.generalNumbersLayout.setObjectName("generalNumbersLayout")
        self.general_telephone_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_telephone_label.setText("Telephone:")
        self.general_telephone_label.setObjectName("general_telephone_label")
        self.generalNumbersLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.general_telephone_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.general_telephone_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_telephone_1.setObjectName("general_telephone_1")
        self.horizontalLayout.addWidget(self.general_telephone_1)
        self.add_general_telephone = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_telephone.setIcon(icon1)
        self.add_general_telephone.setObjectName("add_general_telephone")
        self.horizontalLayout.addWidget(self.add_general_telephone)
        self.generalNumbersLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.general_mobile_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_mobile_label.setText("Mobile:")
        self.general_mobile_label.setObjectName("general_mobile_label")
        self.generalNumbersLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.general_mobile_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.general_mobile_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_mobile_1.setObjectName("general_mobile_1")
        self.horizontalLayout_3.addWidget(self.general_mobile_1)
        self.add_general_mobile = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_mobile.setIcon(icon1)
        self.add_general_mobile.setObjectName("add_general_mobile")
        self.horizontalLayout_3.addWidget(self.add_general_mobile)
        self.generalNumbersLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.general_video_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_video_label.setText("Video call:")
        self.general_video_label.setObjectName("general_video_label")
        self.generalNumbersLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.general_video_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.general_video_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_video_1.setObjectName("general_video_1")
        self.horizontalLayout_2.addWidget(self.general_video_1)
        self.add_general_video = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_video.setIcon(icon1)
        self.add_general_video.setObjectName("add_general_video")
        self.horizontalLayout_2.addWidget(self.add_general_video)
        self.generalNumbersLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.general_fax_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_fax_label.setText("Fax:")
        self.general_fax_label.setObjectName("general_fax_label")
        self.generalNumbersLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.general_fax_label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.general_fax_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_fax_1.setObjectName("general_fax_1")
        self.horizontalLayout_4.addWidget(self.general_fax_1)
        self.add_general_fax = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_fax.setIcon(icon1)
        self.add_general_fax.setObjectName("add_general_fax")
        self.horizontalLayout_4.addWidget(self.add_general_fax)
        self.generalNumbersLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.general_pager_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_pager_label.setText("Pager:")
        self.general_pager_label.setObjectName("general_pager_label")
        self.generalNumbersLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.general_pager_label)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.general_pager_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_pager_1.setObjectName("general_pager_1")
        self.horizontalLayout_5.addWidget(self.general_pager_1)
        self.add_general_pager = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_pager.setIcon(icon1)
        self.add_general_pager.setObjectName("add_general_pager")
        self.horizontalLayout_5.addWidget(self.add_general_pager)
        self.generalNumbersLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.general_internettel_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_internettel_label.setText("Internet telephone:")
        self.general_internettel_label.setObjectName("general_internettel_label")
        self.generalNumbersLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.general_internettel_label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.general_internettel_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_internettel_1.setObjectName("general_internettel_1")
        self.horizontalLayout_6.addWidget(self.general_internettel_1)
        self.add_general_internettel = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_internettel.setIcon(icon1)
        self.add_general_internettel.setObjectName("add_general_internettel")
        self.horizontalLayout_6.addWidget(self.add_general_internettel)
        self.generalNumbersLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.general_ptt_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_ptt_label.setText("Push to talk:")
        self.general_ptt_label.setObjectName("general_ptt_label")
        self.generalNumbersLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.general_ptt_label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.general_ptt_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_ptt_1.setObjectName("general_ptt_1")
        self.horizontalLayout_7.addWidget(self.general_ptt_1)
        self.add_general_ptt = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_ptt.setIcon(icon1)
        self.add_general_ptt.setObjectName("add_general_ptt")
        self.horizontalLayout_7.addWidget(self.add_general_ptt)
        self.generalNumbersLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.general_shareview_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_shareview_label.setText("Share view:")
        self.general_shareview_label.setObjectName("general_shareview_label")
        self.generalNumbersLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.general_shareview_label)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.general_shareview_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_shareview_1.setObjectName("general_shareview_1")
        self.horizontalLayout_8.addWidget(self.general_shareview_1)
        self.add_general_shareview = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_shareview.setIcon(icon1)
        self.add_general_shareview.setObjectName("add_general_shareview")
        self.horizontalLayout_8.addWidget(self.add_general_shareview)
        self.generalNumbersLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.general_sip_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_sip_label.setText("SIP:")
        self.general_sip_label.setObjectName("general_sip_label")
        self.generalNumbersLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.general_sip_label)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.general_sip_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_sip_1.setObjectName("general_sip_1")
        self.horizontalLayout_9.addWidget(self.general_sip_1)
        self.add_general_sip = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_sip.setIcon(icon1)
        self.add_general_sip.setObjectName("add_general_sip")
        self.horizontalLayout_9.addWidget(self.add_general_sip)
        self.generalNumbersLayout.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.general_mail_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_mail_label.setText("E-mail:")
        self.general_mail_label.setObjectName("general_mail_label")
        self.generalNumbersLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.general_mail_label)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.general_mail_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_mail_1.setObjectName("general_mail_1")
        self.horizontalLayout_10.addWidget(self.general_mail_1)
        self.add_general_mail = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_mail.setIcon(icon1)
        self.add_general_mail.setObjectName("add_general_mail")
        self.horizontalLayout_10.addWidget(self.add_general_mail)
        self.generalNumbersLayout.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.general_web_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_web_label.setText("Web address:")
        self.general_web_label.setObjectName("general_web_label")
        self.generalNumbersLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.general_web_label)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.general_web_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_web_1.setObjectName("general_web_1")
        self.horizontalLayout_11.addWidget(self.general_web_1)
        self.add_general_web = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_web.setIcon(icon1)
        self.add_general_web.setObjectName("add_general_web")
        self.horizontalLayout_11.addWidget(self.add_general_web)
        self.generalNumbersLayout.setLayout(10, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.general_dtmf_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.general_dtmf_label.setText("DTMF:")
        self.general_dtmf_label.setObjectName("general_dtmf_label")
        self.generalNumbersLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.general_dtmf_label)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.general_dtmf_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.general_dtmf_1.setObjectName("general_dtmf_1")
        self.horizontalLayout_12.addWidget(self.general_dtmf_1)
        self.add_general_dtmf = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.add_general_dtmf.setIcon(icon1)
        self.add_general_dtmf.setObjectName("add_general_dtmf")
        self.horizontalLayout_12.addWidget(self.add_general_dtmf)
        self.generalNumbersLayout.setLayout(11, QtGui.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.verticalLayout_5.addLayout(self.generalNumbersLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_29.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.generalTab, "")
        self.homeTab = QtGui.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.homeTab)
        self.horizontalLayout_27.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(8, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_26 = QtGui.QLabel(self.homeTab)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.home_address = QtGui.QTextBrowser(self.homeTab)
        self.home_address.setEnabled(False)
        self.home_address.setObjectName("home_address")
        self.verticalLayout_7.addWidget(self.home_address)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.editHomeAddressButton = QtGui.QPushButton(self.homeTab)
        self.editHomeAddressButton.setObjectName("editHomeAddressButton")
        self.horizontalLayout_24.addWidget(self.editHomeAddressButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        spacerItem4 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_27.addLayout(self.verticalLayout_7)
        self.line_6 = QtGui.QFrame(self.homeTab)
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_27.addWidget(self.line_6)
        self.scrollArea_2 = QtGui.QScrollArea(self.homeTab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 398, 537))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.homeNumbersLayout = QtGui.QFormLayout()
        self.homeNumbersLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.homeNumbersLayout.setContentsMargins(5, 5, 8, 5)
        self.homeNumbersLayout.setObjectName("homeNumbersLayout")
        self.home_telephone_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_telephone_label.setText("Telephone:")
        self.home_telephone_label.setObjectName("home_telephone_label")
        self.homeNumbersLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.home_telephone_label)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.home_telephone_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_telephone_1.setObjectName("home_telephone_1")
        self.horizontalLayout_22.addWidget(self.home_telephone_1)
        self.add_home_telephone = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_telephone.setIcon(icon1)
        self.add_home_telephone.setObjectName("add_home_telephone")
        self.horizontalLayout_22.addWidget(self.add_home_telephone)
        self.homeNumbersLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.home_mobile_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_mobile_label.setText("Mobile:")
        self.home_mobile_label.setObjectName("home_mobile_label")
        self.homeNumbersLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.home_mobile_label)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.home_mobile_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_mobile_1.setObjectName("home_mobile_1")
        self.horizontalLayout_25.addWidget(self.home_mobile_1)
        self.add_home_mobile = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_mobile.setIcon(icon1)
        self.add_home_mobile.setObjectName("add_home_mobile")
        self.horizontalLayout_25.addWidget(self.add_home_mobile)
        self.homeNumbersLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_25)
        self.home_video_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_video_label.setText("Video call:")
        self.home_video_label.setObjectName("home_video_label")
        self.homeNumbersLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.home_video_label)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.home_video_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_video_1.setObjectName("home_video_1")
        self.horizontalLayout_26.addWidget(self.home_video_1)
        self.add_home_video = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_video.setIcon(icon1)
        self.add_home_video.setObjectName("add_home_video")
        self.horizontalLayout_26.addWidget(self.add_home_video)
        self.homeNumbersLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_26)
        self.home_fax_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_fax_label.setText("Fax:")
        self.home_fax_label.setObjectName("home_fax_label")
        self.homeNumbersLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.home_fax_label)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.home_fax_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_fax_1.setObjectName("home_fax_1")
        self.horizontalLayout_40.addWidget(self.home_fax_1)
        self.add_home_fax = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_fax.setIcon(icon1)
        self.add_home_fax.setObjectName("add_home_fax")
        self.horizontalLayout_40.addWidget(self.add_home_fax)
        self.homeNumbersLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_40)
        self.home_internettel_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_internettel_label.setText("Internet telephone:")
        self.home_internettel_label.setObjectName("home_internettel_label")
        self.homeNumbersLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.home_internettel_label)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.home_internettel_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_internettel_1.setObjectName("home_internettel_1")
        self.horizontalLayout_41.addWidget(self.home_internettel_1)
        self.add_home_internettel = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_internettel.setIcon(icon1)
        self.add_home_internettel.setObjectName("add_home_internettel")
        self.horizontalLayout_41.addWidget(self.add_home_internettel)
        self.homeNumbersLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_41)
        self.home_mail_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_mail_label.setText("E-mail:")
        self.home_mail_label.setObjectName("home_mail_label")
        self.homeNumbersLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.home_mail_label)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.home_mail_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_mail_1.setObjectName("home_mail_1")
        self.horizontalLayout_45.addWidget(self.home_mail_1)
        self.add_home_mail = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_mail.setIcon(icon1)
        self.add_home_mail.setObjectName("add_home_mail")
        self.horizontalLayout_45.addWidget(self.add_home_mail)
        self.homeNumbersLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_45)
        self.home_web_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.home_web_label.setText("Web address:")
        self.home_web_label.setObjectName("home_web_label")
        self.homeNumbersLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.home_web_label)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.home_web_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.home_web_1.setObjectName("home_web_1")
        self.horizontalLayout_46.addWidget(self.home_web_1)
        self.add_home_web = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.add_home_web.setIcon(icon1)
        self.add_home_web.setObjectName("add_home_web")
        self.horizontalLayout_46.addWidget(self.add_home_web)
        self.homeNumbersLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_46)
        self.verticalLayout_8.addLayout(self.homeNumbersLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_27.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.homeTab, "")
        self.businessTab = QtGui.QWidget()
        self.businessTab.setObjectName("businessTab")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.businessTab)
        self.horizontalLayout_38.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(8, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtGui.QLabel(self.businessTab)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.business_address = QtGui.QTextBrowser(self.businessTab)
        self.business_address.setEnabled(False)
        self.business_address.setObjectName("business_address")
        self.verticalLayout_6.addWidget(self.business_address)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.editBusinessAddressButton = QtGui.QPushButton(self.businessTab)
        self.editBusinessAddressButton.setObjectName("editBusinessAddressButton")
        self.horizontalLayout_23.addWidget(self.editBusinessAddressButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        spacerItem6 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_38.addLayout(self.verticalLayout_6)
        self.line_5 = QtGui.QFrame(self.businessTab)
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_38.addWidget(self.line_5)
        self.scrollArea_3 = QtGui.QScrollArea(self.businessTab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.scrollArea_3)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 398, 537))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.businessNumbersLayout = QtGui.QFormLayout()
        self.businessNumbersLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.businessNumbersLayout.setContentsMargins(5, 5, 8, 5)
        self.businessNumbersLayout.setObjectName("businessNumbersLayout")
        self.business_telephone_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_telephone_label.setText("Telephone:")
        self.business_telephone_label.setObjectName("business_telephone_label")
        self.businessNumbersLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.business_telephone_label)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.business_telephone_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_telephone_1.setObjectName("business_telephone_1")
        self.horizontalLayout_19.addWidget(self.business_telephone_1)
        self.add_business_telephone = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_telephone.setIcon(icon1)
        self.add_business_telephone.setObjectName("add_business_telephone")
        self.horizontalLayout_19.addWidget(self.add_business_telephone)
        self.businessNumbersLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.business_mobile_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_mobile_label.setText("Mobile:")
        self.business_mobile_label.setObjectName("business_mobile_label")
        self.businessNumbersLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.business_mobile_label)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.business_mobile_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_mobile_1.setObjectName("business_mobile_1")
        self.horizontalLayout_20.addWidget(self.business_mobile_1)
        self.add_business_mobile = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_mobile.setIcon(icon1)
        self.add_business_mobile.setObjectName("add_business_mobile")
        self.horizontalLayout_20.addWidget(self.add_business_mobile)
        self.businessNumbersLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.business_video_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_video_label.setText("Video call:")
        self.business_video_label.setObjectName("business_video_label")
        self.businessNumbersLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.business_video_label)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.business_video_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_video_1.setObjectName("business_video_1")
        self.horizontalLayout_21.addWidget(self.business_video_1)
        self.add_business_video = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_video.setIcon(icon1)
        self.add_business_video.setObjectName("add_business_video")
        self.horizontalLayout_21.addWidget(self.add_business_video)
        self.businessNumbersLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.business_fax_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_fax_label.setText("Fax:")
        self.business_fax_label.setObjectName("business_fax_label")
        self.businessNumbersLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.business_fax_label)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.business_fax_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_fax_1.setObjectName("business_fax_1")
        self.horizontalLayout_37.addWidget(self.business_fax_1)
        self.add_business_fax = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_fax.setIcon(icon1)
        self.add_business_fax.setObjectName("add_business_fax")
        self.horizontalLayout_37.addWidget(self.add_business_fax)
        self.businessNumbersLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_37)
        self.business_internettel_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_internettel_label.setText("Internet telephone:")
        self.business_internettel_label.setObjectName("business_internettel_label")
        self.businessNumbersLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.business_internettel_label)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.business_internettel_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_internettel_1.setObjectName("business_internettel_1")
        self.horizontalLayout_39.addWidget(self.business_internettel_1)
        self.add_business_internettel = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_internettel.setIcon(icon1)
        self.add_business_internettel.setObjectName("add_business_internettel")
        self.horizontalLayout_39.addWidget(self.add_business_internettel)
        self.businessNumbersLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_39)
        self.business_mail_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_mail_label.setText("E-mail:")
        self.business_mail_label.setObjectName("business_mail_label")
        self.businessNumbersLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.business_mail_label)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.business_mail_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_mail_1.setObjectName("business_mail_1")
        self.horizontalLayout_43.addWidget(self.business_mail_1)
        self.add_business_mail = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_mail.setIcon(icon1)
        self.add_business_mail.setObjectName("add_business_mail")
        self.horizontalLayout_43.addWidget(self.add_business_mail)
        self.businessNumbersLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_43)
        self.business_web_label = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.business_web_label.setText("Web address:")
        self.business_web_label.setObjectName("business_web_label")
        self.businessNumbersLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.business_web_label)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.business_web_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.business_web_1.setObjectName("business_web_1")
        self.horizontalLayout_44.addWidget(self.business_web_1)
        self.add_business_web = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.add_business_web.setIcon(icon1)
        self.add_business_web.setObjectName("add_business_web")
        self.horizontalLayout_44.addWidget(self.add_business_web)
        self.businessNumbersLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_44)
        self.verticalLayout_9.addLayout(self.businessNumbersLayout)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_38.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.businessTab, "")
        self.notesTab = QtGui.QWidget()
        self.notesTab.setObjectName("notesTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.notesTab)
        self.verticalLayout_4.setContentsMargins(14, 10, 14, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.notesLayout = QtGui.QVBoxLayout()
        self.notesLayout.setObjectName("notesLayout")
        self.label_30 = QtGui.QLabel(self.notesTab)
        self.label_30.setObjectName("label_30")
        self.notesLayout.addWidget(self.label_30)
        self.notes_1 = QtGui.QTextEdit(self.notesTab)
        self.notes_1.setObjectName("notes_1")
        self.notesLayout.addWidget(self.notes_1)
        self.verticalLayout_4.addLayout(self.notesLayout)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.add_note = QtGui.QPushButton(self.notesTab)
        self.add_note.setIcon(icon1)
        self.add_note.setObjectName("add_note")
        self.horizontalLayout_28.addWidget(self.add_note)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.tabWidget.addTab(self.notesTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(ContactsEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.nickname_label.setBuddy(self.nickname)
        self.company_label.setBuddy(self.company)
        self.jobtitle_label.setBuddy(self.jobtitle_1)
        self.birthday_label.setBuddy(self.birthday)
        self.label_7.setBuddy(self.groups)
        self.general_telephone_label.setBuddy(self.general_telephone_1)
        self.general_mobile_label.setBuddy(self.general_mobile_1)
        self.general_video_label.setBuddy(self.general_video_1)
        self.general_fax_label.setBuddy(self.general_fax_1)
        self.general_pager_label.setBuddy(self.general_pager_1)
        self.general_internettel_label.setBuddy(self.general_internettel_1)
        self.general_ptt_label.setBuddy(self.general_ptt_1)
        self.general_shareview_label.setBuddy(self.general_shareview_1)
        self.general_sip_label.setBuddy(self.general_sip_1)
        self.general_mail_label.setBuddy(self.general_mail_1)
        self.general_web_label.setBuddy(self.general_web_1)
        self.general_dtmf_label.setBuddy(self.general_dtmf_1)
        self.home_telephone_label.setBuddy(self.home_telephone_1)
        self.home_mobile_label.setBuddy(self.home_mobile_1)
        self.home_video_label.setBuddy(self.home_video_1)
        self.home_fax_label.setBuddy(self.home_fax_1)
        self.home_internettel_label.setBuddy(self.home_internettel_1)
        self.home_mail_label.setBuddy(self.home_mail_1)
        self.home_web_label.setBuddy(self.home_web_1)
        self.business_telephone_label.setBuddy(self.business_telephone_1)
        self.business_mobile_label.setBuddy(self.business_mobile_1)
        self.business_video_label.setBuddy(self.business_video_1)
        self.business_fax_label.setBuddy(self.business_fax_1)
        self.business_internettel_label.setBuddy(self.business_internettel_1)
        self.business_mail_label.setBuddy(self.business_mail_1)
        self.business_web_label.setBuddy(self.business_web_1)

        self.retranslateUi(ContactsEdit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ContactsEdit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ContactsEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(ContactsEdit)

    def retranslateUi(self, ContactsEdit):
        ContactsEdit.setWindowTitle(QtGui.QApplication.translate("ContactsEdit", "New contact...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ContactsEdit", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.editNameButton.setText(QtGui.QApplication.translate("ContactsEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ContactsEdit", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.editGeneralAddressButton.setText(QtGui.QApplication.translate("ContactsEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ContactsEdit", "Groups:", None, QtGui.QApplication.UnicodeUTF8))
        self.editGroupsButton.setText(QtGui.QApplication.translate("ContactsEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), QtGui.QApplication.translate("ContactsEdit", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("ContactsEdit", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.editHomeAddressButton.setText(QtGui.QApplication.translate("ContactsEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), QtGui.QApplication.translate("ContactsEdit", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ContactsEdit", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.editBusinessAddressButton.setText(QtGui.QApplication.translate("ContactsEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.businessTab), QtGui.QApplication.translate("ContactsEdit", "Business", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("ContactsEdit", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.add_note.setText(QtGui.QApplication.translate("ContactsEdit", "New note", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notesTab), QtGui.QApplication.translate("ContactsEdit", "Notes", None, QtGui.QApplication.UnicodeUTF8))

from widget.ImageButton import ImageButton
import resource_rc
