# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/calendar_edit.ui'
#
# Created: Wed Nov 17 12:05:53 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CalendarEntryEdit(object):
    def setupUi(self, CalendarEntryEdit):
        CalendarEntryEdit.setObjectName("CalendarEntryEdit")
        CalendarEntryEdit.resize(543, 313)
        CalendarEntryEdit.setWindowTitle("New calendar entry")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/view-calendar"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CalendarEntryEdit.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(CalendarEntryEdit)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(10, 10, 15, 15)
        self.formLayout.setHorizontalSpacing(3)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(CalendarEntryEdit)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.titleLine = QtGui.QLineEdit(CalendarEntryEdit)
        self.titleLine.setObjectName("titleLine")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.titleLine)
        self.label_2 = QtGui.QLabel(CalendarEntryEdit)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.locationLine = QtGui.QLineEdit(CalendarEntryEdit)
        self.locationLine.setObjectName("locationLine")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.locationLine)
        self.label_3 = QtGui.QLabel(CalendarEntryEdit)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startDate = QtGui.QDateEdit(CalendarEntryEdit)
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.horizontalLayout_5.addWidget(self.startDate)
        self.startTime = QtGui.QTimeEdit(CalendarEntryEdit)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_5.addWidget(self.startTime)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_4 = QtGui.QLabel(CalendarEntryEdit)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.endDate = QtGui.QDateEdit(CalendarEntryEdit)
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.horizontalLayout_6.addWidget(self.endDate)
        self.endTime = QtGui.QTimeEdit(CalendarEntryEdit)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_6.addWidget(self.endTime)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(4, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.recurrenceLabel = QtGui.QLabel(CalendarEntryEdit)
        self.recurrenceLabel.setObjectName("recurrenceLabel")
        self.horizontalLayout_4.addWidget(self.recurrenceLabel)
        self.recurrenceButton = QtGui.QPushButton(CalendarEntryEdit)
        self.recurrenceButton.setObjectName("recurrenceButton")
        self.horizontalLayout_4.addWidget(self.recurrenceButton)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtGui.QLabel(CalendarEntryEdit)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(4, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reminderCheckBox = QtGui.QCheckBox(CalendarEntryEdit)
        self.reminderCheckBox.setObjectName("reminderCheckBox")
        self.horizontalLayout_3.addWidget(self.reminderCheckBox)
        self.reminderStack = QtGui.QStackedWidget(CalendarEntryEdit)
        self.reminderStack.setObjectName("reminderStack")
        self.basicReminderWidget = QtGui.QWidget()
        self.basicReminderWidget.setObjectName("basicReminderWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.basicReminderWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reminderTimeBox = QtGui.QSpinBox(self.basicReminderWidget)
        self.reminderTimeBox.setEnabled(False)
        self.reminderTimeBox.setMinimumSize(QtCore.QSize(70, 0))
        self.reminderTimeBox.setMaximum(500)
        self.reminderTimeBox.setObjectName("reminderTimeBox")
        self.horizontalLayout.addWidget(self.reminderTimeBox)
        self.reminderUnitBox = QtGui.QComboBox(self.basicReminderWidget)
        self.reminderUnitBox.setEnabled(False)
        self.reminderUnitBox.setMinimumSize(QtCore.QSize(110, 0))
        self.reminderUnitBox.setObjectName("reminderUnitBox")
        self.horizontalLayout.addWidget(self.reminderUnitBox)
        self.reminderStack.addWidget(self.basicReminderWidget)
        self.advancedReminderWidget = QtGui.QWidget()
        self.advancedReminderWidget.setObjectName("advancedReminderWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.advancedReminderWidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reminderDateTime = QtGui.QDateTimeEdit(self.advancedReminderWidget)
        self.reminderDateTime.setEnabled(False)
        self.reminderDateTime.setObjectName("reminderDateTime")
        self.horizontalLayout_2.addWidget(self.reminderDateTime)
        self.reminderStack.addWidget(self.advancedReminderWidget)
        self.horizontalLayout_3.addWidget(self.reminderStack)
        self.reminderAdvancedButton = QtGui.QPushButton(CalendarEntryEdit)
        self.reminderAdvancedButton.setEnabled(False)
        self.reminderAdvancedButton.setCheckable(True)
        self.reminderAdvancedButton.setObjectName("reminderAdvancedButton")
        self.horizontalLayout_3.addWidget(self.reminderAdvancedButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_7 = QtGui.QLabel(CalendarEntryEdit)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.priorityBox = QtGui.QComboBox(CalendarEntryEdit)
        self.priorityBox.setMinimumSize(QtCore.QSize(150, 0))
        self.priorityBox.setObjectName("priorityBox")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.priorityBox)
        self.label_8 = QtGui.QLabel(CalendarEntryEdit)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.accessBox = QtGui.QComboBox(CalendarEntryEdit)
        self.accessBox.setMinimumSize(QtCore.QSize(150, 0))
        self.accessBox.setObjectName("accessBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.accessBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(CalendarEntryEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.titleLine)
        self.label_2.setBuddy(self.locationLine)
        self.label_3.setBuddy(self.startDate)
        self.label_4.setBuddy(self.endDate)
        self.recurrenceLabel.setBuddy(self.recurrenceButton)
        self.label_6.setBuddy(self.reminderCheckBox)
        self.label_7.setBuddy(self.priorityBox)
        self.label_8.setBuddy(self.accessBox)

        self.retranslateUi(CalendarEntryEdit)
        self.reminderStack.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CalendarEntryEdit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CalendarEntryEdit.reject)
        QtCore.QObject.connect(self.reminderCheckBox, QtCore.SIGNAL("toggled(bool)"), self.reminderTimeBox.setEnabled)
        QtCore.QObject.connect(self.reminderCheckBox, QtCore.SIGNAL("toggled(bool)"), self.reminderUnitBox.setEnabled)
        QtCore.QObject.connect(self.reminderCheckBox, QtCore.SIGNAL("toggled(bool)"), self.reminderAdvancedButton.setEnabled)
        QtCore.QObject.connect(self.titleLine, QtCore.SIGNAL("textEdited(QString)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.locationLine, QtCore.SIGNAL("textEdited(QString)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.startDate, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.startTime, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.endDate, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.endTime, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.reminderCheckBox, QtCore.SIGNAL("clicked()"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.priorityBox, QtCore.SIGNAL("currentIndexChanged(int)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.accessBox, QtCore.SIGNAL("currentIndexChanged(int)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.reminderTimeBox, QtCore.SIGNAL("editingFinished()"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.reminderUnitBox, QtCore.SIGNAL("currentIndexChanged(int)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.reminderDateTime, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), CalendarEntryEdit.entryChanged)
        QtCore.QObject.connect(self.reminderCheckBox, QtCore.SIGNAL("toggled(bool)"), self.reminderDateTime.setEnabled)
        QtCore.QObject.connect(self.reminderAdvancedButton, QtCore.SIGNAL("toggled(bool)"), CalendarEntryEdit.setAdvancedReminder)
        QtCore.QMetaObject.connectSlotsByName(CalendarEntryEdit)
        CalendarEntryEdit.setTabOrder(self.titleLine, self.locationLine)
        CalendarEntryEdit.setTabOrder(self.locationLine, self.startDate)
        CalendarEntryEdit.setTabOrder(self.startDate, self.startTime)
        CalendarEntryEdit.setTabOrder(self.startTime, self.endDate)
        CalendarEntryEdit.setTabOrder(self.endDate, self.endTime)
        CalendarEntryEdit.setTabOrder(self.endTime, self.recurrenceButton)
        CalendarEntryEdit.setTabOrder(self.recurrenceButton, self.reminderCheckBox)
        CalendarEntryEdit.setTabOrder(self.reminderCheckBox, self.reminderTimeBox)
        CalendarEntryEdit.setTabOrder(self.reminderTimeBox, self.reminderUnitBox)
        CalendarEntryEdit.setTabOrder(self.reminderUnitBox, self.reminderAdvancedButton)
        CalendarEntryEdit.setTabOrder(self.reminderAdvancedButton, self.priorityBox)
        CalendarEntryEdit.setTabOrder(self.priorityBox, self.accessBox)
        CalendarEntryEdit.setTabOrder(self.accessBox, self.buttonBox)

    def retranslateUi(self, CalendarEntryEdit):
        self.label.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CalendarEntryEdit", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceLabel.setText(QtGui.QApplication.translate("CalendarEntryEdit", "No recurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceButton.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Reminder:", None, QtGui.QApplication.UnicodeUTF8))
        self.reminderCheckBox.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Reminder:", None, QtGui.QApplication.UnicodeUTF8))
        self.reminderAdvancedButton.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Advanced...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CalendarEntryEdit", "Access:", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
