# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/calendar_edit_recurrence.ui'
#
# Created: Wed Nov 17 12:05:54 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CalendarEntryRecurrenceEdit(object):
    def setupUi(self, CalendarEntryRecurrenceEdit):
        CalendarEntryRecurrenceEdit.setObjectName("CalendarEntryRecurrenceEdit")
        CalendarEntryRecurrenceEdit.resize(696, 532)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/view-calendar"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CalendarEntryRecurrenceEdit.setWindowIcon(icon)
        self.verticalLayout_7 = QtGui.QVBoxLayout(CalendarEntryRecurrenceEdit)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setContentsMargins(10, 15, 10, 15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.recurrenceBox = QtGui.QCheckBox(CalendarEntryRecurrenceEdit)
        self.recurrenceBox.setObjectName("recurrenceBox")
        self.verticalLayout_7.addWidget(self.recurrenceBox)
        self.recurrenceWidget = QtGui.QWidget(CalendarEntryRecurrenceEdit)
        self.recurrenceWidget.setEnabled(False)
        self.recurrenceWidget.setObjectName("recurrenceWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.recurrenceWidget)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtGui.QGroupBox(self.recurrenceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtGui.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.dailyButton = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dailyButton.sizePolicy().hasHeightForWidth())
        self.dailyButton.setSizePolicy(sizePolicy)
        self.dailyButton.setObjectName("dailyButton")
        self.verticalLayout_9.addWidget(self.dailyButton)
        self.weeklyButton = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weeklyButton.sizePolicy().hasHeightForWidth())
        self.weeklyButton.setSizePolicy(sizePolicy)
        self.weeklyButton.setChecked(True)
        self.weeklyButton.setObjectName("weeklyButton")
        self.verticalLayout_9.addWidget(self.weeklyButton)
        self.monthlyButton = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monthlyButton.sizePolicy().hasHeightForWidth())
        self.monthlyButton.setSizePolicy(sizePolicy)
        self.monthlyButton.setObjectName("monthlyButton")
        self.verticalLayout_9.addWidget(self.monthlyButton)
        self.yearlyButton = QtGui.QRadioButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearlyButton.sizePolicy().hasHeightForWidth())
        self.yearlyButton.setSizePolicy(sizePolicy)
        self.yearlyButton.setObjectName("yearlyButton")
        self.verticalLayout_9.addWidget(self.yearlyButton)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout.addWidget(self.widget_2)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ruleWidget = QtGui.QStackedWidget(self.groupBox)
        self.ruleWidget.setObjectName("ruleWidget")
        self.dailyWidget = QtGui.QWidget()
        self.dailyWidget.setObjectName("dailyWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dailyWidget)
        self.horizontalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.dailyWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.recurDayBox = QtGui.QSpinBox(self.dailyWidget)
        self.recurDayBox.setMinimum(1)
        self.recurDayBox.setMaximum(999)
        self.recurDayBox.setObjectName("recurDayBox")
        self.horizontalLayout_2.addWidget(self.recurDayBox)
        self.label_3 = QtGui.QLabel(self.dailyWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ruleWidget.addWidget(self.dailyWidget)
        self.weeklyWidget = QtGui.QWidget()
        self.weeklyWidget.setObjectName("weeklyWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.weeklyWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, -1, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.weeklyWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.recurWeekBox = QtGui.QSpinBox(self.weeklyWidget)
        self.recurWeekBox.setMinimum(1)
        self.recurWeekBox.setMaximum(200)
        self.recurWeekBox.setObjectName("recurWeekBox")
        self.horizontalLayout_3.addWidget(self.recurWeekBox)
        self.label_5 = QtGui.QLabel(self.weeklyWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(25, -1, 30, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mondayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.mondayBox.setText("Mon")
        self.mondayBox.setObjectName("mondayBox")
        self.horizontalLayout_4.addWidget(self.mondayBox)
        self.tuesdayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.tuesdayBox.setText("Tue")
        self.tuesdayBox.setObjectName("tuesdayBox")
        self.horizontalLayout_4.addWidget(self.tuesdayBox)
        self.wednesdayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.wednesdayBox.setText("Wed")
        self.wednesdayBox.setObjectName("wednesdayBox")
        self.horizontalLayout_4.addWidget(self.wednesdayBox)
        self.thursdayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.thursdayBox.setText("Thu")
        self.thursdayBox.setObjectName("thursdayBox")
        self.horizontalLayout_4.addWidget(self.thursdayBox)
        self.fridayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.fridayBox.setText("Fri")
        self.fridayBox.setObjectName("fridayBox")
        self.horizontalLayout_4.addWidget(self.fridayBox)
        self.saturdayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.saturdayBox.setText("Sat")
        self.saturdayBox.setObjectName("saturdayBox")
        self.horizontalLayout_4.addWidget(self.saturdayBox)
        self.sundayBox = QtGui.QCheckBox(self.weeklyWidget)
        self.sundayBox.setText("Sun")
        self.sundayBox.setObjectName("sundayBox")
        self.horizontalLayout_4.addWidget(self.sundayBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.ruleWidget.addWidget(self.weeklyWidget)
        self.monthlyWidget = QtGui.QWidget()
        self.monthlyWidget.setObjectName("monthlyWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.monthlyWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 10, -1, 15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.monthlyWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.recurMonthBox = QtGui.QSpinBox(self.monthlyWidget)
        self.recurMonthBox.setMinimum(1)
        self.recurMonthBox.setObjectName("recurMonthBox")
        self.horizontalLayout_5.addWidget(self.recurMonthBox)
        self.label_6 = QtGui.QLabel(self.monthlyWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.monthlyByDatesButton = QtGui.QRadioButton(self.monthlyWidget)
        self.monthlyByDatesButton.setChecked(True)
        self.monthlyByDatesButton.setObjectName("monthlyByDatesButton")
        self.horizontalLayout_6.addWidget(self.monthlyByDatesButton)
        self.monthlyDayInMonthBox = QtGui.QComboBox(self.monthlyWidget)
        self.monthlyDayInMonthBox.setObjectName("monthlyDayInMonthBox")
        self.horizontalLayout_6.addWidget(self.monthlyDayInMonthBox)
        self.label_8 = QtGui.QLabel(self.monthlyWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.monthlyByDaysButton = QtGui.QRadioButton(self.monthlyWidget)
        self.monthlyByDaysButton.setObjectName("monthlyByDaysButton")
        self.horizontalLayout_7.addWidget(self.monthlyByDaysButton)
        self.monthlyWeekInMonthBox = QtGui.QComboBox(self.monthlyWidget)
        self.monthlyWeekInMonthBox.setObjectName("monthlyWeekInMonthBox")
        self.horizontalLayout_7.addWidget(self.monthlyWeekInMonthBox)
        self.monthlyDayInWeekBox = QtGui.QComboBox(self.monthlyWidget)
        self.monthlyDayInWeekBox.setMinimumSize(QtCore.QSize(125, 0))
        self.monthlyDayInWeekBox.setObjectName("monthlyDayInWeekBox")
        self.horizontalLayout_7.addWidget(self.monthlyDayInWeekBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.ruleWidget.addWidget(self.monthlyWidget)
        self.yearlyWidget = QtGui.QWidget()
        self.yearlyWidget.setObjectName("yearlyWidget")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.yearlyWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 10, -1, 15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtGui.QLabel(self.yearlyWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.recurYearBox = QtGui.QSpinBox(self.yearlyWidget)
        self.recurYearBox.setMinimum(1)
        self.recurYearBox.setObjectName("recurYearBox")
        self.horizontalLayout_8.addWidget(self.recurYearBox)
        self.label_9 = QtGui.QLabel(self.yearlyWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.yearlyByDateButton = QtGui.QRadioButton(self.yearlyWidget)
        self.yearlyByDateButton.setChecked(True)
        self.yearlyByDateButton.setObjectName("yearlyByDateButton")
        self.horizontalLayout_9.addWidget(self.yearlyByDateButton)
        self.yearlyDayInMonthBox = QtGui.QSpinBox(self.yearlyWidget)
        self.yearlyDayInMonthBox.setMinimum(1)
        self.yearlyDayInMonthBox.setMaximum(31)
        self.yearlyDayInMonthBox.setObjectName("yearlyDayInMonthBox")
        self.horizontalLayout_9.addWidget(self.yearlyDayInMonthBox)
        self.label_11 = QtGui.QLabel(self.yearlyWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.yearlyMonthInYearBox_ByDate = QtGui.QComboBox(self.yearlyWidget)
        self.yearlyMonthInYearBox_ByDate.setMinimumSize(QtCore.QSize(125, 0))
        self.yearlyMonthInYearBox_ByDate.setObjectName("yearlyMonthInYearBox_ByDate")
        self.horizontalLayout_9.addWidget(self.yearlyMonthInYearBox_ByDate)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(25, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.yearlyByDaysButton = QtGui.QRadioButton(self.yearlyWidget)
        self.yearlyByDaysButton.setObjectName("yearlyByDaysButton")
        self.horizontalLayout_10.addWidget(self.yearlyByDaysButton)
        self.yearlyWeekInMonthBox = QtGui.QComboBox(self.yearlyWidget)
        self.yearlyWeekInMonthBox.setObjectName("yearlyWeekInMonthBox")
        self.horizontalLayout_10.addWidget(self.yearlyWeekInMonthBox)
        self.yearlyDayInWeekBox = QtGui.QComboBox(self.yearlyWidget)
        self.yearlyDayInWeekBox.setMinimumSize(QtCore.QSize(125, 0))
        self.yearlyDayInWeekBox.setObjectName("yearlyDayInWeekBox")
        self.horizontalLayout_10.addWidget(self.yearlyDayInWeekBox)
        self.label_12 = QtGui.QLabel(self.yearlyWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.yearlyMonthInYearBox_ByDay = QtGui.QComboBox(self.yearlyWidget)
        self.yearlyMonthInYearBox_ByDay.setMinimumSize(QtCore.QSize(125, 0))
        self.yearlyMonthInYearBox_ByDay.setObjectName("yearlyMonthInYearBox_ByDay")
        self.horizontalLayout_10.addWidget(self.yearlyMonthInYearBox_ByDay)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.ruleWidget.addWidget(self.yearlyWidget)
        self.verticalLayout_4.addWidget(self.ruleWidget)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_2 = QtGui.QGroupBox(self.recurrenceWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(6, 15, 6, -1)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.startDate = QtGui.QDateEdit(self.groupBox_2)
        self.startDate.setEnabled(False)
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.endDate = QtGui.QDateEdit(self.groupBox_2)
        self.endDate.setEnabled(False)
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.gridLayout.addWidget(self.endDate, 1, 1, 1, 1)
        self.endingDateBox = QtGui.QCheckBox(self.groupBox_2)
        self.endingDateBox.setChecked(True)
        self.endingDateBox.setObjectName("endingDateBox")
        self.gridLayout.addWidget(self.endingDateBox, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 2, 0, 1, 3)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.recurrenceWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_11.setContentsMargins(6, 7, 6, 7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.exceptionDateEdit = QtGui.QDateEdit(self.groupBox_3)
        self.exceptionDateEdit.setCalendarPopup(True)
        self.exceptionDateEdit.setObjectName("exceptionDateEdit")
        self.verticalLayout_5.addWidget(self.exceptionDateEdit)
        self.exceptionAddButton = QtGui.QPushButton(self.groupBox_3)
        self.exceptionAddButton.setObjectName("exceptionAddButton")
        self.verticalLayout_5.addWidget(self.exceptionAddButton)
        self.exceptionDeleteButton = QtGui.QPushButton(self.groupBox_3)
        self.exceptionDeleteButton.setObjectName("exceptionDeleteButton")
        self.verticalLayout_5.addWidget(self.exceptionDeleteButton)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.exceptionList = QtGui.QListWidget(self.groupBox_3)
        self.exceptionList.setObjectName("exceptionList")
        self.horizontalLayout_11.addWidget(self.exceptionList)
        self.horizontalLayout_12.addWidget(self.groupBox_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7.addWidget(self.recurrenceWidget)
        self.buttonBox = QtGui.QDialogButtonBox(CalendarEntryRecurrenceEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_7.addWidget(self.buttonBox)
        self.label_13.setBuddy(self.startDate)
        self.label_14.setBuddy(self.endDate)

        self.retranslateUi(CalendarEntryRecurrenceEdit)
        self.ruleWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CalendarEntryRecurrenceEdit.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CalendarEntryRecurrenceEdit.reject)
        QtCore.QObject.connect(self.recurrenceBox, QtCore.SIGNAL("toggled(bool)"), self.recurrenceWidget.setEnabled)
        QtCore.QObject.connect(self.endingDateBox, QtCore.SIGNAL("toggled(bool)"), self.endDate.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(CalendarEntryRecurrenceEdit)

    def retranslateUi(self, CalendarEntryRecurrenceEdit):
        CalendarEntryRecurrenceEdit.setWindowTitle(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Edit recurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.recurrenceBox.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Enable recurrence", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recurrence Rule", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recurrence Types", None, QtGui.QApplication.UnicodeUTF8))
        self.dailyButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Daily", None, QtGui.QApplication.UnicodeUTF8))
        self.weeklyButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Weekly", None, QtGui.QApplication.UnicodeUTF8))
        self.monthlyButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Monthly", None, QtGui.QApplication.UnicodeUTF8))
        self.yearlyButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Yearly", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "day(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "week(s) on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "month(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.monthlyByDatesButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur on the", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "day", None, QtGui.QApplication.UnicodeUTF8))
        self.monthlyByDaysButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur on the", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "year(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.yearlyByDateButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur on day", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.yearlyByDaysButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recur on the", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Recurrence Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Start date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Ending date:", None, QtGui.QApplication.UnicodeUTF8))
        self.endingDateBox.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "No ending date", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "Exceptions", None, QtGui.QApplication.UnicodeUTF8))
        self.exceptionAddButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.exceptionDeleteButton.setText(QtGui.QApplication.translate("CalendarEntryRecurrenceEdit", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.exceptionList.setSortingEnabled(True)

import resource_rc
