# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/contacts_import.ui'
#
# Created: Wed Nov 17 12:06:00 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ContactsImport(object):
    def setupUi(self, ContactsImport):
        ContactsImport.setObjectName("ContactsImport")
        ContactsImport.resize(570, 507)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/document-import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ContactsImport.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ContactsImport)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setContentsMargins(7, 10, 7, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contactsSplitter = QtGui.QSplitter(ContactsImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsSplitter.sizePolicy().hasHeightForWidth())
        self.contactsSplitter.setSizePolicy(sizePolicy)
        self.contactsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.contactsSplitter.setHandleWidth(12)
        self.contactsSplitter.setObjectName("contactsSplitter")
        self.layoutWidget_4 = QtGui.QWidget(self.contactsSplitter)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.contactsList = QtGui.QListWidget(self.layoutWidget_4)
        self.contactsList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.contactsList.setSpacing(1)
        self.contactsList.setObjectName("contactsList")
        self.verticalLayout_6.addWidget(self.contactsList)
        self.layoutWidget = QtGui.QWidget(self.contactsSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.contactBrowser = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactBrowser.sizePolicy().hasHeightForWidth())
        self.contactBrowser.setSizePolicy(sizePolicy)
        self.contactBrowser.setObjectName("contactBrowser")
        self.verticalLayout_11.addWidget(self.contactBrowser)
        self.verticalLayout_2.addWidget(self.contactsSplitter)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectFileButton = QtGui.QPushButton(ContactsImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFileButton.sizePolicy().hasHeightForWidth())
        self.selectFileButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/document-open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectFileButton.setIcon(icon1)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout_6.addWidget(self.selectFileButton)
        self.contactsAddButton = QtGui.QPushButton(ContactsImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsAddButton.sizePolicy().hasHeightForWidth())
        self.contactsAddButton.setSizePolicy(sizePolicy)
        self.contactsAddButton.setIcon(icon)
        self.contactsAddButton.setAutoDefault(False)
        self.contactsAddButton.setObjectName("contactsAddButton")
        self.horizontalLayout_6.addWidget(self.contactsAddButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(ContactsImport)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(ContactsImport)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ContactsImport.reject)
        QtCore.QMetaObject.connectSlotsByName(ContactsImport)

    def retranslateUi(self, ContactsImport):
        ContactsImport.setWindowTitle(QtGui.QApplication.translate("ContactsImport", "Import contacts...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ContactsImport", "Contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsList.setSortingEnabled(True)
        self.label.setText(QtGui.QApplication.translate("ContactsImport", "Details:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectFileButton.setText(QtGui.QApplication.translate("ContactsImport", "Open File...", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsAddButton.setText(QtGui.QApplication.translate("ContactsImport", "Import contacts", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
