# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/export.ui'
#
# Created: Wed Nov 17 12:05:59 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Export(object):
    def setupUi(self, Export):
        Export.setObjectName("Export")
        Export.resize(495, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/document-export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Export.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Export)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setContentsMargins(6, 5, 6, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settingsBox = QtGui.QGroupBox(Export)
        self.settingsBox.setObjectName("settingsBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.settingsBox)
        self.gridLayout_2.setContentsMargins(15, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.settingsBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.formatBox = QtGui.QComboBox(self.settingsBox)
        self.formatBox.setObjectName("formatBox")
        self.gridLayout_2.addWidget(self.formatBox, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.settingsBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.contactsBox = QtGui.QCheckBox(self.settingsBox)
        self.contactsBox.setChecked(True)
        self.contactsBox.setObjectName("contactsBox")
        self.horizontalLayout_4.addWidget(self.contactsBox)
        self.messagesBox = QtGui.QCheckBox(self.settingsBox)
        self.messagesBox.setChecked(True)
        self.messagesBox.setObjectName("messagesBox")
        self.horizontalLayout_4.addWidget(self.messagesBox)
        self.calendarBox = QtGui.QCheckBox(self.settingsBox)
        self.calendarBox.setChecked(True)
        self.calendarBox.setObjectName("calendarBox")
        self.horizontalLayout_4.addWidget(self.calendarBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.settingsBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.exportLine = QtGui.QLineEdit(self.settingsBox)
        self.exportLine.setObjectName("exportLine")
        self.gridLayout_2.addWidget(self.exportLine, 2, 1, 1, 1)
        self.openBrowserButton = QtGui.QToolButton(self.settingsBox)
        self.openBrowserButton.setText("...")
        self.openBrowserButton.setObjectName("openBrowserButton")
        self.gridLayout_2.addWidget(self.openBrowserButton, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 3, 1, 1)
        self.directoryLabel = QtGui.QLabel(self.settingsBox)
        self.directoryLabel.setObjectName("directoryLabel")
        self.gridLayout_2.addWidget(self.directoryLabel, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.settingsBox)
        self.contactBox = QtGui.QGroupBox(Export)
        self.contactBox.setObjectName("contactBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.contactBox)
        self.verticalLayout.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allContactsButton = QtGui.QRadioButton(self.contactBox)
        self.allContactsButton.setChecked(True)
        self.allContactsButton.setObjectName("allContactsButton")
        self.verticalLayout.addWidget(self.allContactsButton)
        self.messageContactsButton = QtGui.QRadioButton(self.contactBox)
        self.messageContactsButton.setObjectName("messageContactsButton")
        self.verticalLayout.addWidget(self.messageContactsButton)
        self.filterButton = QtGui.QRadioButton(self.contactBox)
        self.filterButton.setObjectName("filterButton")
        self.verticalLayout.addWidget(self.filterButton)
        self.contactsList = QtGui.QListWidget(self.contactBox)
        self.contactsList.setEnabled(False)
        self.contactsList.setObjectName("contactsList")
        self.verticalLayout.addWidget(self.contactsList)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectAllButton = QtGui.QPushButton(self.contactBox)
        self.selectAllButton.setEnabled(False)
        self.selectAllButton.setObjectName("selectAllButton")
        self.horizontalLayout.addWidget(self.selectAllButton)
        self.deselectAllButton = QtGui.QPushButton(self.contactBox)
        self.deselectAllButton.setEnabled(False)
        self.deselectAllButton.setObjectName("deselectAllButton")
        self.horizontalLayout.addWidget(self.deselectAllButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.contactBox)
        self.pluginSettingsBox = QtGui.QGroupBox(Export)
        self.pluginSettingsBox.setObjectName("pluginSettingsBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pluginSettingsBox)
        self.verticalLayout_5.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.periodLabel = QtGui.QLabel(self.pluginSettingsBox)
        self.periodLabel.setObjectName("periodLabel")
        self.gridLayout.addWidget(self.periodLabel, 0, 0, 1, 1)
        self.periodBox = QtGui.QComboBox(self.pluginSettingsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodBox.sizePolicy().hasHeightForWidth())
        self.periodBox.setSizePolicy(sizePolicy)
        self.periodBox.setObjectName("periodBox")
        self.gridLayout.addWidget(self.periodBox, 0, 1, 1, 1)
        self.orderLabel = QtGui.QLabel(self.pluginSettingsBox)
        self.orderLabel.setObjectName("orderLabel")
        self.gridLayout.addWidget(self.orderLabel, 1, 0, 1, 1)
        self.orderBox = QtGui.QComboBox(self.pluginSettingsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderBox.sizePolicy().hasHeightForWidth())
        self.orderBox.setSizePolicy(sizePolicy)
        self.orderBox.setObjectName("orderBox")
        self.gridLayout.addWidget(self.orderBox, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.graphBox = QtGui.QCheckBox(self.pluginSettingsBox)
        self.graphBox.setChecked(True)
        self.graphBox.setObjectName("graphBox")
        self.verticalLayout_5.addWidget(self.graphBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphFormatLabel = QtGui.QLabel(self.pluginSettingsBox)
        self.graphFormatLabel.setObjectName("graphFormatLabel")
        self.horizontalLayout_2.addWidget(self.graphFormatLabel)
        self.graphFormatBox = QtGui.QComboBox(self.pluginSettingsBox)
        self.graphFormatBox.setObjectName("graphFormatBox")
        self.horizontalLayout_2.addWidget(self.graphFormatBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.legendBox = QtGui.QCheckBox(self.pluginSettingsBox)
        self.legendBox.setChecked(True)
        self.legendBox.setObjectName("legendBox")
        self.verticalLayout_2.addWidget(self.legendBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.thumbnailsBox = QtGui.QCheckBox(self.pluginSettingsBox)
        self.thumbnailsBox.setChecked(True)
        self.thumbnailsBox.setObjectName("thumbnailsBox")
        self.verticalLayout_5.addWidget(self.thumbnailsBox)
        self.verticalLayout_3.addWidget(self.pluginSettingsBox)
        self.buttonBox = QtGui.QDialogButtonBox(Export)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Export)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Export.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Export.reject)
        QtCore.QObject.connect(self.filterButton, QtCore.SIGNAL("toggled(bool)"), self.contactsList.setEnabled)
        QtCore.QObject.connect(self.filterButton, QtCore.SIGNAL("toggled(bool)"), self.selectAllButton.setEnabled)
        QtCore.QObject.connect(self.filterButton, QtCore.SIGNAL("toggled(bool)"), self.deselectAllButton.setEnabled)
        QtCore.QObject.connect(self.graphBox, QtCore.SIGNAL("toggled(bool)"), self.graphFormatLabel.setEnabled)
        QtCore.QObject.connect(self.graphBox, QtCore.SIGNAL("toggled(bool)"), self.graphFormatBox.setEnabled)
        QtCore.QObject.connect(self.graphBox, QtCore.SIGNAL("toggled(bool)"), self.legendBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Export)

    def retranslateUi(self, Export):
        Export.setWindowTitle(QtGui.QApplication.translate("Export", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsBox.setTitle(QtGui.QApplication.translate("Export", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Export", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Export", "Export items:", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsBox.setText(QtGui.QApplication.translate("Export", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.messagesBox.setText(QtGui.QApplication.translate("Export", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.calendarBox.setText(QtGui.QApplication.translate("Export", "Calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Export", "Export directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryLabel.setText(QtGui.QApplication.translate("Export", "No export directory selected!", None, QtGui.QApplication.UnicodeUTF8))
        self.contactBox.setTitle(QtGui.QApplication.translate("Export", "Contact export...", None, QtGui.QApplication.UnicodeUTF8))
        self.allContactsButton.setText(QtGui.QApplication.translate("Export", "Export all contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.messageContactsButton.setText(QtGui.QApplication.translate("Export", "Only export contacts with at least one message", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("Export", "Filter contacts and show only messages from these contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllButton.setText(QtGui.QApplication.translate("Export", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.deselectAllButton.setText(QtGui.QApplication.translate("Export", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginSettingsBox.setTitle(QtGui.QApplication.translate("Export", "Plugin settings", None, QtGui.QApplication.UnicodeUTF8))
        self.periodLabel.setText(QtGui.QApplication.translate("Export", "Period per file:", None, QtGui.QApplication.UnicodeUTF8))
        self.orderLabel.setText(QtGui.QApplication.translate("Export", "Message order:", None, QtGui.QApplication.UnicodeUTF8))
        self.graphBox.setText(QtGui.QApplication.translate("Export", "Include statistics graph", None, QtGui.QApplication.UnicodeUTF8))
        self.graphFormatLabel.setText(QtGui.QApplication.translate("Export", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.legendBox.setText(QtGui.QApplication.translate("Export", "Show legend", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbnailsBox.setText(QtGui.QApplication.translate("Export", "Show thumbnail images for contacts", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
