# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/favorites.ui'
#
# Created: Wed Nov 17 12:06:01 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Favorites(object):
    def setupUi(self, Favorites):
        Favorites.setObjectName("Favorites")
        Favorites.resize(600, 562)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Favorites)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtGui.QGroupBox(Favorites)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.favoriteContactsList = QtGui.QListWidget(self.groupBox_7)
        self.favoriteContactsList.setObjectName("favoriteContactsList")
        self.verticalLayout_12.addWidget(self.favoriteContactsList)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.addContactButton = QtGui.QPushButton(self.groupBox_7)
        self.addContactButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/go-previous"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addContactButton.setIcon(icon)
        self.addContactButton.setObjectName("addContactButton")
        self.verticalLayout_13.addWidget(self.addContactButton)
        self.removeContactButton = QtGui.QPushButton(self.groupBox_7)
        self.removeContactButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/go-next"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeContactButton.setIcon(icon1)
        self.removeContactButton.setObjectName("removeContactButton")
        self.verticalLayout_13.addWidget(self.removeContactButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.allContactsList = QtGui.QListWidget(self.groupBox_7)
        self.allContactsList.setObjectName("allContactsList")
        self.verticalLayout_14.addWidget(self.allContactsList)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_2 = QtGui.QGroupBox(Favorites)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.noDynamicButtonButton = QtGui.QRadioButton(self.groupBox_2)
        self.noDynamicButtonButton.setObjectName("noDynamicButtonButton")
        self.verticalLayout.addWidget(self.noDynamicButtonButton)
        self.showDynFavoritesButton = QtGui.QRadioButton(self.groupBox_2)
        self.showDynFavoritesButton.setObjectName("showDynFavoritesButton")
        self.verticalLayout.addWidget(self.showDynFavoritesButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showDynFavoritesWithDaysButton = QtGui.QRadioButton(self.groupBox_2)
        self.showDynFavoritesWithDaysButton.setChecked(True)
        self.showDynFavoritesWithDaysButton.setObjectName("showDynFavoritesWithDaysButton")
        self.horizontalLayout.addWidget(self.showDynFavoritesWithDaysButton)
        self.dayBox = QtGui.QSpinBox(self.groupBox_2)
        self.dayBox.setSuffix("")
        self.dayBox.setMinimum(1)
        self.dayBox.setMaximum(600)
        self.dayBox.setProperty("value", 15)
        self.dayBox.setObjectName("dayBox")
        self.horizontalLayout.addWidget(self.dayBox)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Favorites)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.submenuBox = QtGui.QCheckBox(self.groupBox)
        self.submenuBox.setObjectName("submenuBox")
        self.verticalLayout_2.addWidget(self.submenuBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.numBox = QtGui.QSpinBox(self.groupBox)
        self.numBox.setMaximum(30)
        self.numBox.setObjectName("numBox")
        self.horizontalLayout_2.addWidget(self.numBox)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(Favorites)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Favorites)
        QtCore.QObject.connect(self.allContactsList, QtCore.SIGNAL("itemDoubleClicked(QListWidgetItem*)"), self.addContactButton.animateClick)
        QtCore.QObject.connect(self.favoriteContactsList, QtCore.SIGNAL("itemDoubleClicked(QListWidgetItem*)"), self.removeContactButton.animateClick)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Favorites.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Favorites.reject)
        QtCore.QObject.connect(self.showDynFavoritesWithDaysButton, QtCore.SIGNAL("toggled(bool)"), self.dayBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Favorites)

    def retranslateUi(self, Favorites):
        Favorites.setWindowTitle(QtGui.QApplication.translate("Favorites", "Manage favorites", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Favorites", "Static favorites", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Favorites", "Favorite contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Favorites", "Available contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Favorites", "Dynamic Favorites", None, QtGui.QApplication.UnicodeUTF8))
        self.noDynamicButtonButton.setText(QtGui.QApplication.translate("Favorites", "Only show favorites from the list above.", None, QtGui.QApplication.UnicodeUTF8))
        self.showDynFavoritesButton.setText(QtGui.QApplication.translate("Favorites", "Show contacts with the most messages.", None, QtGui.QApplication.UnicodeUTF8))
        self.showDynFavoritesWithDaysButton.setText(QtGui.QApplication.translate("Favorites", "Show contacts with the most messages within the last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Favorites", "days.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Favorites", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.submenuBox.setText(QtGui.QApplication.translate("Favorites", "Show favorites in a sub-menu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Favorites", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Favorites", "dynamic favorites", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
