# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/history.ui'
#
# Created: Wed Nov 17 12:06:03 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(670, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/message-history"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        History.setWindowIcon(icon)
        History.setSizeGripEnabled(False)
        History.setModal(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(History)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(History)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.contactBox = QtGui.QComboBox(History)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactBox.sizePolicy().hasHeightForWidth())
        self.contactBox.setSizePolicy(sizePolicy)
        self.contactBox.setObjectName("contactBox")
        self.horizontalLayout_2.addWidget(self.contactBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(History)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.filterBox = QtGui.QComboBox(History)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterBox.sizePolicy().hasHeightForWidth())
        self.filterBox.setSizePolicy(sizePolicy)
        self.filterBox.setObjectName("filterBox")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.horizontalLayout.addWidget(self.filterBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter = QtGui.QSplitter(History)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.dateTree = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dateTree.sizePolicy().hasHeightForWidth())
        self.dateTree.setSizePolicy(sizePolicy)
        self.dateTree.setAnimated(True)
        self.dateTree.setObjectName("dateTree")
        self.messageBrowser = QtGui.QTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.messageBrowser.sizePolicy().hasHeightForWidth())
        self.messageBrowser.setSizePolicy(sizePolicy)
        self.messageBrowser.setObjectName("messageBrowser")
        self.verticalLayout_2.addWidget(self.splitter)
        self.searchWidget = QtGui.QWidget(History)
        self.searchWidget.setObjectName("searchWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.searchWidget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtGui.QFrame(self.searchWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.searchWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.searchText = QtGui.QLineEdit(self.searchWidget)
        self.searchText.setObjectName("searchText")
        self.gridLayout.addWidget(self.searchText, 0, 1, 1, 1)
        self.olderBox = QtGui.QCheckBox(self.searchWidget)
        self.olderBox.setObjectName("olderBox")
        self.gridLayout.addWidget(self.olderBox, 1, 0, 1, 1)
        self.olderDate = QtGui.QDateEdit(self.searchWidget)
        self.olderDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.olderDate.sizePolicy().hasHeightForWidth())
        self.olderDate.setSizePolicy(sizePolicy)
        self.olderDate.setObjectName("olderDate")
        self.gridLayout.addWidget(self.olderDate, 1, 1, 1, 1)
        self.newerBox = QtGui.QCheckBox(self.searchWidget)
        self.newerBox.setObjectName("newerBox")
        self.gridLayout.addWidget(self.newerBox, 2, 0, 1, 1)
        self.newerDate = QtGui.QDateEdit(self.searchWidget)
        self.newerDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newerDate.sizePolicy().hasHeightForWidth())
        self.newerDate.setSizePolicy(sizePolicy)
        self.newerDate.setObjectName("newerDate")
        self.gridLayout.addWidget(self.newerDate, 2, 1, 1, 1)
        self.applyButton = QtGui.QPushButton(self.searchWidget)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout.addWidget(self.applyButton, 3, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(250, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.searchWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchButton = QtGui.QPushButton(History)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/go-up"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon1)
        self.searchButton.setCheckable(True)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_4.addWidget(self.searchButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(History)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(History)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), History.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), History.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), History.reject)
        QtCore.QObject.connect(self.olderBox, QtCore.SIGNAL("clicked(bool)"), self.olderDate.setEnabled)
        QtCore.QObject.connect(self.newerBox, QtCore.SIGNAL("clicked(bool)"), self.newerDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(History)
        History.setTabOrder(self.dateTree, self.messageBrowser)
        History.setTabOrder(self.messageBrowser, self.contactBox)
        History.setTabOrder(self.contactBox, self.filterBox)

    def retranslateUi(self, History):
        History.setWindowTitle(QtGui.QApplication.translate("History", "View history", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("History", "Contact:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("History", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(0, QtGui.QApplication.translate("History", "All messages", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(1, QtGui.QApplication.translate("History", "Only incoming", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(2, QtGui.QApplication.translate("History", "Only outgoing", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTree.headerItem().setText(0, QtGui.QApplication.translate("History", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("History", "Log contents:", None, QtGui.QApplication.UnicodeUTF8))
        self.olderBox.setText(QtGui.QApplication.translate("History", "Only older than", None, QtGui.QApplication.UnicodeUTF8))
        self.newerBox.setText(QtGui.QApplication.translate("History", "Only newer than", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("History", "Apply filter...", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("History", "Search messages...", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setShortcut(QtGui.QApplication.translate("History", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
