# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/main.ui'
#
# Created: Wed Nov 17 12:05:50 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 613)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/phone"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setMaximumSize(QtCore.QSize(70, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 136, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 136, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.listWidget.setPalette(palette)
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged)
        self.listWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.listWidget.setIconSize(QtCore.QSize(32, 32))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setResizeMode(QtGui.QListView.Fixed)
        self.listWidget.setLayoutMode(QtGui.QListView.SinglePass)
        self.listWidget.setGridSize(QtCore.QSize(70, 55))
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setWordWrap(False)
        self.listWidget.setObjectName("listWidget")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/summary"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/summary"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/messages"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/messages"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/contacts"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/contacts"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/view-calendar"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/inode-directory"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/phone"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/phone"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon6)
        self.horizontalLayout.addWidget(self.listWidget)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.summary = QtGui.QWidget()
        self.summary.setObjectName("summary")
        self.verticalLayout = QtGui.QVBoxLayout(self.summary)
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusLabel = QtGui.QLabel(self.summary)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_3.addWidget(self.statusLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_5 = QtGui.QFrame(self.summary)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.connectionStack = QtGui.QStackedWidget(self.summary)
        self.connectionStack.setObjectName("connectionStack")
        self.connectionWidget = QtGui.QWidget()
        self.connectionWidget.setObjectName("connectionWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.connectionWidget)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName("_2")
        self.devicesBox = DeviceDatabaseViewCombobox(self.connectionWidget)
        self.devicesBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesBox.sizePolicy().hasHeightForWidth())
        self.devicesBox.setSizePolicy(sizePolicy)
        self.devicesBox.setObjectName("devicesBox")
        self._2.addWidget(self.devicesBox)
        self.connectButton = QtGui.QPushButton(self.connectionWidget)
        self.connectButton.setObjectName("connectButton")
        self._2.addWidget(self.connectButton)
        self.scanningMovie = QtGui.QLabel(self.connectionWidget)
        self.scanningMovie.setMinimumSize(QtCore.QSize(16, 16))
        self.scanningMovie.setMaximumSize(QtCore.QSize(16, 16))
        self.scanningMovie.setText("")
        self.scanningMovie.setObjectName("scanningMovie")
        self._2.addWidget(self.scanningMovie)
        spacerItem = QtGui.QSpacerItem(375, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self._2)
        self.establishConnectionStack = QtGui.QStackedWidget(self.connectionWidget)
        self.establishConnectionStack.setObjectName("establishConnectionStack")
        self.establishConnectionWidget = QtGui.QWidget()
        self.establishConnectionWidget.setObjectName("establishConnectionWidget")
        self.gridLayout = QtGui.QGridLayout(self.establishConnectionWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtGui.QSpacerItem(628, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 3)
        self.connectLabel = QtGui.QLabel(self.establishConnectionWidget)
        self.connectLabel.setObjectName("connectLabel")
        self.gridLayout.addWidget(self.connectLabel, 1, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(628, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 3)
        self.connectBar = QtGui.QProgressBar(self.establishConnectionWidget)
        self.connectBar.setMaximum(5)
        self.connectBar.setProperty("value", 0)
        self.connectBar.setObjectName("connectBar")
        self.gridLayout.addWidget(self.connectBar, 3, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(498, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.cancelButton = QtGui.QPushButton(self.establishConnectionWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 4, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(5, 15, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtGui.QLabel(self.establishConnectionWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.establishConnectionWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.establishConnectionWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.establishConnectionWidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 3, 0, 1, 1)
        self.connectionStateLabel = QtGui.QLabel(self.establishConnectionWidget)
        self.connectionStateLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.connectionStateLabel.setText("")
        self.connectionStateLabel.setObjectName("connectionStateLabel")
        self.gridLayout_5.addWidget(self.connectionStateLabel, 0, 1, 1, 1)
        self.sysinfoStateLabel = QtGui.QLabel(self.establishConnectionWidget)
        self.sysinfoStateLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.sysinfoStateLabel.setText("")
        self.sysinfoStateLabel.setObjectName("sysinfoStateLabel")
        self.gridLayout_5.addWidget(self.sysinfoStateLabel, 1, 1, 1, 1)
        self.contactStateLabel = QtGui.QLabel(self.establishConnectionWidget)
        self.contactStateLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.contactStateLabel.setText("")
        self.contactStateLabel.setObjectName("contactStateLabel")
        self.gridLayout_5.addWidget(self.contactStateLabel, 2, 1, 1, 1)
        self.calendarStateLabel = QtGui.QLabel(self.establishConnectionWidget)
        self.calendarStateLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.calendarStateLabel.setText("")
        self.calendarStateLabel.setObjectName("calendarStateLabel")
        self.gridLayout_5.addWidget(self.calendarStateLabel, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 5, 0, 1, 1)
        self.establishConnectionStack.addWidget(self.establishConnectionWidget)
        self.emptyWidget = QtGui.QWidget()
        self.emptyWidget.setObjectName("emptyWidget")
        self.establishConnectionStack.addWidget(self.emptyWidget)
        self.verticalLayout_2.addWidget(self.establishConnectionStack)
        spacerItem5 = QtGui.QSpacerItem(20, 321, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.connectionStack.addWidget(self.connectionWidget)
        self.informationWidget = QtGui.QWidget()
        self.informationWidget.setObjectName("informationWidget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.informationWidget)
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(13, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_22 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.connectionTimeLabel_2 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionTimeLabel_2.sizePolicy().hasHeightForWidth())
        self.connectionTimeLabel_2.setSizePolicy(sizePolicy)
        self.connectionTimeLabel_2.setObjectName("connectionTimeLabel_2")
        self.gridLayout_2.addWidget(self.connectionTimeLabel_2, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(17, 148, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 5, 1)
        spacerItem7 = QtGui.QSpacerItem(388, 145, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 4, 5, 1)
        self.label_28 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 0, 1, 1)
        self.refreshTimeLabel_2 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshTimeLabel_2.sizePolicy().hasHeightForWidth())
        self.refreshTimeLabel_2.setSizePolicy(sizePolicy)
        self.refreshTimeLabel_2.setObjectName("refreshTimeLabel_2")
        self.gridLayout_2.addWidget(self.refreshTimeLabel_2, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 0, 1, 1)
        self.modelLabel_2 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel_2.sizePolicy().hasHeightForWidth())
        self.modelLabel_2.setSizePolicy(sizePolicy)
        self.modelLabel_2.setObjectName("modelLabel_2")
        self.gridLayout_2.addWidget(self.modelLabel_2, 2, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 3, 0, 1, 1)
        self.batteryLabel_2 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryLabel_2.sizePolicy().hasHeightForWidth())
        self.batteryLabel_2.setSizePolicy(sizePolicy)
        self.batteryLabel_2.setObjectName("batteryLabel_2")
        self.gridLayout_2.addWidget(self.batteryLabel_2, 3, 1, 1, 1)
        self.batteryBar_2 = QtGui.QProgressBar(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryBar_2.sizePolicy().hasHeightForWidth())
        self.batteryBar_2.setSizePolicy(sizePolicy)
        self.batteryBar_2.setMinimumSize(QtCore.QSize(111, 0))
        self.batteryBar_2.setMaximumSize(QtCore.QSize(1000, 26))
        self.batteryBar_2.setProperty("value", 0)
        self.batteryBar_2.setObjectName("batteryBar_2")
        self.gridLayout_2.addWidget(self.batteryBar_2, 3, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 4, 0, 1, 1)
        self.signalLabel_2 = QtGui.QLabel(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalLabel_2.sizePolicy().hasHeightForWidth())
        self.signalLabel_2.setSizePolicy(sizePolicy)
        self.signalLabel_2.setObjectName("signalLabel_2")
        self.gridLayout_2.addWidget(self.signalLabel_2, 4, 1, 1, 1)
        self.signalBar_2 = QtGui.QProgressBar(self.informationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalBar_2.sizePolicy().hasHeightForWidth())
        self.signalBar_2.setSizePolicy(sizePolicy)
        self.signalBar_2.setMaximumSize(QtCore.QSize(111, 26))
        self.signalBar_2.setMinimum(1)
        self.signalBar_2.setMaximum(4)
        self.signalBar_2.setProperty("value", 4)
        self.signalBar_2.setObjectName("signalBar_2")
        self.gridLayout_2.addWidget(self.signalBar_2, 4, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem8 = QtGui.QSpacerItem(20, 301, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.connectionStack.addWidget(self.informationWidget)
        self.verticalLayout.addWidget(self.connectionStack)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem9)
        self.refreshButton = QtGui.QPushButton(self.summary)
        self.refreshButton.setEnabled(False)
        self.refreshButton.setObjectName("refreshButton")
        self.hboxlayout.addWidget(self.refreshButton)
        self.disconnectButton = QtGui.QPushButton(self.summary)
        self.disconnectButton.setEnabled(False)
        self.disconnectButton.setObjectName("disconnectButton")
        self.hboxlayout.addWidget(self.disconnectButton)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.line_2 = QtGui.QFrame(self.summary)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.stackedWidget.addWidget(self.summary)
        self.messages = QtGui.QWidget()
        self.messages.setObjectName("messages")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.messages)
        self.verticalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.messages)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.toLine = QtGui.QLineEdit(self.messages)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toLine.sizePolicy().hasHeightForWidth())
        self.toLine.setSizePolicy(sizePolicy)
        self.toLine.setObjectName("toLine")
        self.horizontalLayout_4.addWidget(self.toLine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.messages)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.messagesSplitter = QtGui.QSplitter(self.messages)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagesSplitter.sizePolicy().hasHeightForWidth())
        self.messagesSplitter.setSizePolicy(sizePolicy)
        self.messagesSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.messagesSplitter.setHandleWidth(12)
        self.messagesSplitter.setObjectName("messagesSplitter")
        self.layoutWidget_2 = QtGui.QWidget(self.messagesSplitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.messageLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.messageLayout.setContentsMargins(-1, 4, -1, -1)
        self.messageLayout.setObjectName("messageLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.messageLayout.addWidget(self.label_3)
        self.messageText = MessageTextEdit(self.layoutWidget_2)
        self.messageText.setObjectName("messageText")
        self.messageLayout.addWidget(self.messageText)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName("_4")
        self.sendButton = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setObjectName("sendButton")
        self._4.addWidget(self.sendButton)
        self.charLabel = QtGui.QLabel(self.layoutWidget_2)
        self.charLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.charLabel.setObjectName("charLabel")
        self._4.addWidget(self.charLabel)
        self.messageLayout.addLayout(self._4)
        self.layoutWidget_3 = QtGui.QWidget(self.messagesSplitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.contactLayout = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.contactLayout.setContentsMargins(-1, 4, -1, -1)
        self.contactLayout.setObjectName("contactLayout")
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.contactLayout.addWidget(self.label_5)
        self.searchLine = SearchLineEdit(self.layoutWidget_3)
        self.searchLine.setText("")
        self.searchLine.setObjectName("searchLine")
        self.contactLayout.addWidget(self.searchLine)
        self.contactsTree = QtGui.QTreeWidget(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsTree.sizePolicy().hasHeightForWidth())
        self.contactsTree.setSizePolicy(sizePolicy)
        self.contactsTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.contactsTree.setIndentation(0)
        self.contactsTree.setItemsExpandable(False)
        self.contactsTree.setObjectName("contactsTree")
        self.contactLayout.addWidget(self.contactsTree)
        self.verticalLayout_3.addWidget(self.messagesSplitter)
        self.stackedWidget.addWidget(self.messages)
        self.contacts = QtGui.QWidget()
        self.contacts.setObjectName("contacts")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.contacts)
        self.verticalLayout_12.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.contactsLayout = QtGui.QHBoxLayout()
        self.contactsLayout.setContentsMargins(-1, -1, -1, 0)
        self.contactsLayout.setObjectName("contactsLayout")
        self.searchLine_2 = SearchLineEdit(self.contacts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLine_2.sizePolicy().hasHeightForWidth())
        self.searchLine_2.setSizePolicy(sizePolicy)
        self.searchLine_2.setObjectName("searchLine_2")
        self.contactsLayout.addWidget(self.searchLine_2)
        self.label_4 = QtGui.QLabel(self.contacts)
        self.label_4.setObjectName("label_4")
        self.contactsLayout.addWidget(self.label_4)
        self.typeBox = QtGui.QComboBox(self.contacts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeBox.sizePolicy().hasHeightForWidth())
        self.typeBox.setSizePolicy(sizePolicy)
        self.typeBox.setObjectName("typeBox")
        self.contactsLayout.addWidget(self.typeBox)
        spacerItem10 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.contactsLayout.addItem(spacerItem10)
        self.label_13 = QtGui.QLabel(self.contacts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.contactsLayout.addWidget(self.label_13)
        self.devicesBox_3 = DeviceDatabaseViewCombobox(self.contacts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesBox_3.sizePolicy().hasHeightForWidth())
        self.devicesBox_3.setSizePolicy(sizePolicy)
        self.devicesBox_3.setObjectName("devicesBox_3")
        self.contactsLayout.addWidget(self.devicesBox_3)
        self.verticalLayout_12.addLayout(self.contactsLayout)
        self.line_6 = QtGui.QFrame(self.contacts)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_12.addWidget(self.line_6)
        self.contactsSplitter = QtGui.QSplitter(self.contacts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsSplitter.sizePolicy().hasHeightForWidth())
        self.contactsSplitter.setSizePolicy(sizePolicy)
        self.contactsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.contactsSplitter.setHandleWidth(12)
        self.contactsSplitter.setObjectName("contactsSplitter")
        self.layoutWidget_4 = QtGui.QWidget(self.contactsSplitter)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.contactsList = QtGui.QListWidget(self.layoutWidget_4)
        self.contactsList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.contactsList.setSpacing(1)
        self.contactsList.setObjectName("contactsList")
        self.verticalLayout_6.addWidget(self.contactsList)
        self.layoutWidget = QtGui.QWidget(self.contactsSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 13, -1, 13)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nameLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setText("")
        self.nameLabel.setTextFormat(QtCore.Qt.RichText)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setWordWrap(True)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_2.addWidget(self.nameLabel)
        self.pictureLabel = QtGui.QLabel(self.layoutWidget)
        self.pictureLabel.setText("")
        self.pictureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pictureLabel.setObjectName("pictureLabel")
        self.horizontalLayout_2.addWidget(self.pictureLabel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.contactBrowser = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactBrowser.sizePolicy().hasHeightForWidth())
        self.contactBrowser.setSizePolicy(sizePolicy)
        self.contactBrowser.setObjectName("contactBrowser")
        self.verticalLayout_11.addWidget(self.contactBrowser)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.contactAddButton = QtGui.QPushButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/list-add-user"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactAddButton.setIcon(icon7)
        self.contactAddButton.setObjectName("contactAddButton")
        self.horizontalLayout_6.addWidget(self.contactAddButton)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.contactEditButton = QtGui.QPushButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/user-properties"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactEditButton.setIcon(icon8)
        self.contactEditButton.setObjectName("contactEditButton")
        self.horizontalLayout_6.addWidget(self.contactEditButton)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.contactsImportButton = QtGui.QPushButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/document-import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactsImportButton.setIcon(icon9)
        self.contactsImportButton.setObjectName("contactsImportButton")
        self.horizontalLayout_6.addWidget(self.contactsImportButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_12.addWidget(self.contactsSplitter)
        self.stackedWidget.addWidget(self.contacts)
        self.calendar = QtGui.QWidget()
        self.calendar.setObjectName("calendar")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.calendar)
        self.verticalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calendarWidget = CalendarView(self.calendar)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.stackedWidget.addWidget(self.calendar)
        self.files = QtGui.QWidget()
        self.files.setObjectName("files")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.files)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fileWidget = ObexWidget(self.files)
        self.fileWidget.setObjectName("fileWidget")
        self.verticalLayout_5.addWidget(self.fileWidget)
        self.stackedWidget.addWidget(self.files)
        self.devices = QtGui.QWidget()
        self.devices.setObjectName("devices")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.devices)
        self.verticalLayout_8.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.devices)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.devicesBox_2 = DeviceDatabaseViewCombobox(self.devices)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devicesBox_2.sizePolicy().hasHeightForWidth())
        self.devicesBox_2.setSizePolicy(sizePolicy)
        self.devicesBox_2.setObjectName("devicesBox_2")
        self.horizontalLayout_5.addWidget(self.devicesBox_2)
        spacerItem13 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(self.devices)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_8.addWidget(self.line_3)
        self.detailStack = QtGui.QStackedWidget(self.devices)
        self.detailStack.setObjectName("detailStack")
        self.extendedWidget = QtGui.QWidget()
        self.extendedWidget.setObjectName("extendedWidget")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.extendedWidget)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.connectionTimeLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionTimeLabel.sizePolicy().hasHeightForWidth())
        self.connectionTimeLabel.setSizePolicy(sizePolicy)
        self.connectionTimeLabel.setObjectName("connectionTimeLabel")
        self.gridLayout_3.addWidget(self.connectionTimeLabel, 1, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 1, 3, 8, 1)
        self.line_4 = QtGui.QFrame(self.extendedWidget)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 4, 8, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 1, 5, 8, 1)
        self.label_20 = QtGui.QLabel(self.extendedWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 6, 1, 1)
        self.drivespaceBox = QtGui.QComboBox(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drivespaceBox.sizePolicy().hasHeightForWidth())
        self.drivespaceBox.setSizePolicy(sizePolicy)
        self.drivespaceBox.setObjectName("drivespaceBox")
        self.drivespaceBox.addItem("")
        self.gridLayout_3.addWidget(self.drivespaceBox, 1, 7, 1, 1)
        self.label = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.refreshTimeLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshTimeLabel.sizePolicy().hasHeightForWidth())
        self.refreshTimeLabel.setSizePolicy(sizePolicy)
        self.refreshTimeLabel.setObjectName("refreshTimeLabel")
        self.gridLayout_3.addWidget(self.refreshTimeLabel, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.extendedWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 6, 1, 1)
        self.imeiLabel = QtGui.QLabel(self.extendedWidget)
        self.imeiLabel.setObjectName("imeiLabel")
        self.gridLayout_3.addWidget(self.imeiLabel, 2, 7, 1, 1)
        self.label_14 = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.modelLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setObjectName("modelLabel")
        self.gridLayout_3.addWidget(self.modelLabel, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.extendedWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 6, 1, 1)
        self.freeRamLabel = QtGui.QLabel(self.extendedWidget)
        self.freeRamLabel.setObjectName("freeRamLabel")
        self.gridLayout_3.addWidget(self.freeRamLabel, 3, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.batteryLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryLabel.sizePolicy().hasHeightForWidth())
        self.batteryLabel.setSizePolicy(sizePolicy)
        self.batteryLabel.setObjectName("batteryLabel")
        self.gridLayout_3.addWidget(self.batteryLabel, 4, 1, 1, 1)
        self.batteryBar = QtGui.QProgressBar(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryBar.sizePolicy().hasHeightForWidth())
        self.batteryBar.setSizePolicy(sizePolicy)
        self.batteryBar.setMinimumSize(QtCore.QSize(111, 0))
        self.batteryBar.setMaximumSize(QtCore.QSize(1000, 20))
        self.batteryBar.setProperty("value", 0)
        self.batteryBar.setObjectName("batteryBar")
        self.gridLayout_3.addWidget(self.batteryBar, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.extendedWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 6, 1, 1)
        self.totalRamLabel = QtGui.QLabel(self.extendedWidget)
        self.totalRamLabel.setObjectName("totalRamLabel")
        self.gridLayout_3.addWidget(self.totalRamLabel, 4, 7, 1, 1)
        self.label_10 = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 0, 1, 1)
        self.signalLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalLabel.sizePolicy().hasHeightForWidth())
        self.signalLabel.setSizePolicy(sizePolicy)
        self.signalLabel.setObjectName("signalLabel")
        self.gridLayout_3.addWidget(self.signalLabel, 5, 1, 1, 1)
        self.signalBar = QtGui.QProgressBar(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalBar.sizePolicy().hasHeightForWidth())
        self.signalBar.setSizePolicy(sizePolicy)
        self.signalBar.setMaximumSize(QtCore.QSize(111, 20))
        self.signalBar.setMinimum(1)
        self.signalBar.setMaximum(4)
        self.signalBar.setProperty("value", 4)
        self.signalBar.setObjectName("signalBar")
        self.gridLayout_3.addWidget(self.signalBar, 5, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.extendedWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 6, 1, 1)
        self.romLabel = QtGui.QLabel(self.extendedWidget)
        self.romLabel.setObjectName("romLabel")
        self.gridLayout_3.addWidget(self.romLabel, 5, 7, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 1, 8, 8, 1)
        self.label_12 = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 1)
        self.profileLabel = QtGui.QLabel(self.extendedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileLabel.sizePolicy().hasHeightForWidth())
        self.profileLabel.setSizePolicy(sizePolicy)
        self.profileLabel.setObjectName("profileLabel")
        self.gridLayout_3.addWidget(self.profileLabel, 6, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.extendedWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 6, 1, 1)
        self.swLabel = QtGui.QLabel(self.extendedWidget)
        self.swLabel.setObjectName("swLabel")
        self.gridLayout_3.addWidget(self.swLabel, 6, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.extendedWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 7, 0, 1, 1)
        self.btAddressLabel = QtGui.QLabel(self.extendedWidget)
        self.btAddressLabel.setObjectName("btAddressLabel")
        self.gridLayout_3.addWidget(self.btAddressLabel, 7, 1, 1, 2)
        self.label_27 = QtGui.QLabel(self.extendedWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 7, 6, 1, 1)
        self.programLabel = QtGui.QLabel(self.extendedWidget)
        self.programLabel.setObjectName("programLabel")
        self.gridLayout_3.addWidget(self.programLabel, 7, 7, 1, 1)
        self.label_18 = QtGui.QLabel(self.extendedWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 8, 0, 1, 1)
        self.displayLabel = QtGui.QLabel(self.extendedWidget)
        self.displayLabel.setObjectName("displayLabel")
        self.gridLayout_3.addWidget(self.displayLabel, 8, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self.extendedWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 8, 6, 1, 1)
        self.osLabel = QtGui.QLabel(self.extendedWidget)
        self.osLabel.setObjectName("osLabel")
        self.gridLayout_3.addWidget(self.osLabel, 8, 7, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.detailStack.addWidget(self.extendedWidget)
        self.simpleWidget = QtGui.QWidget()
        self.simpleWidget.setObjectName("simpleWidget")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.simpleWidget)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtGui.QLabel(self.simpleWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.modelLabel_3 = QtGui.QLabel(self.simpleWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel_3.sizePolicy().hasHeightForWidth())
        self.modelLabel_3.setSizePolicy(sizePolicy)
        self.modelLabel_3.setObjectName("modelLabel_3")
        self.gridLayout_4.addWidget(self.modelLabel_3, 1, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.simpleWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 2, 0, 1, 1)
        self.imeiLabel_3 = QtGui.QLabel(self.simpleWidget)
        self.imeiLabel_3.setObjectName("imeiLabel_3")
        self.gridLayout_4.addWidget(self.imeiLabel_3, 2, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.simpleWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 3, 0, 1, 1)
        self.totalRamLabel_3 = QtGui.QLabel(self.simpleWidget)
        self.totalRamLabel_3.setObjectName("totalRamLabel_3")
        self.gridLayout_4.addWidget(self.totalRamLabel_3, 3, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.simpleWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 4, 0, 1, 1)
        self.romLabel_3 = QtGui.QLabel(self.simpleWidget)
        self.romLabel_3.setObjectName("romLabel_3")
        self.gridLayout_4.addWidget(self.romLabel_3, 4, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.simpleWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.simpleWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 6, 0, 1, 1)
        self.displayLabel_3 = QtGui.QLabel(self.simpleWidget)
        self.displayLabel_3.setObjectName("displayLabel_3")
        self.gridLayout_4.addWidget(self.displayLabel_3, 5, 1, 1, 1)
        self.osLabel_3 = QtGui.QLabel(self.simpleWidget)
        self.osLabel_3.setObjectName("osLabel_3")
        self.gridLayout_4.addWidget(self.osLabel_3, 6, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 2, 7, 1)
        self.label_9 = QtGui.QLabel(self.simpleWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 2)
        self.verticalLayout_10.addLayout(self.gridLayout_4)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem18)
        self.detailStack.addWidget(self.simpleWidget)
        self.noDataWidget = QtGui.QWidget()
        self.noDataWidget.setObjectName("noDataWidget")
        self.detailStack.addWidget(self.noDataWidget)
        self.verticalLayout_8.addWidget(self.detailStack)
        spacerItem19 = QtGui.QSpacerItem(298, 269, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem19)
        self.stackedWidget.addWidget(self.devices)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Messages = QtGui.QMenu(self.menubar)
        self.menu_Messages.setObjectName("menu_Messages")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Contacts = QtGui.QMenu(self.menubar)
        self.menu_Contacts.setObjectName("menu_Contacts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newMessageAction = QtGui.QAction(MainWindow)
        self.newMessageAction.setEnabled(False)
        self.newMessageAction.setVisible(False)
        self.newMessageAction.setObjectName("newMessageAction")
        self.quitAction = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/application-exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon10)
        self.quitAction.setObjectName("quitAction")
        self.saveMessagesAction = QtGui.QAction(MainWindow)
        self.saveMessagesAction.setEnabled(False)
        self.saveMessagesAction.setVisible(False)
        self.saveMessagesAction.setObjectName("saveMessagesAction")
        self.exportMessagesAction = QtGui.QAction(MainWindow)
        self.exportMessagesAction.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/document-export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportMessagesAction.setIcon(icon11)
        self.exportMessagesAction.setVisible(False)
        self.exportMessagesAction.setObjectName("exportMessagesAction")
        self.importMessagesAction = QtGui.QAction(MainWindow)
        self.importMessagesAction.setIcon(icon9)
        self.importMessagesAction.setObjectName("importMessagesAction")
        self.settingsAction = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/configure"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsAction.setIcon(icon12)
        self.settingsAction.setObjectName("settingsAction")
        self.aboutQtAction = QtGui.QAction(MainWindow)
        self.aboutQtAction.setObjectName("aboutQtAction")
        self.messageQueueAction = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/messages"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messageQueueAction.setIcon(icon13)
        self.messageQueueAction.setObjectName("messageQueueAction")
        self.historyAction = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/message-history"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyAction.setIcon(icon14)
        self.historyAction.setObjectName("historyAction")
        self.logAction = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/text-plain"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logAction.setIcon(icon15)
        self.logAction.setObjectName("logAction")
        self.aboutApplicationAction = QtGui.QAction(MainWindow)
        self.aboutApplicationAction.setIcon(icon)
        self.aboutApplicationAction.setObjectName("aboutApplicationAction")
        self.statisticsAction = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/view-statistics"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statisticsAction.setIcon(icon16)
        self.statisticsAction.setObjectName("statisticsAction")
        self.donateAction = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/summary"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donateAction.setIcon(icon17)
        self.donateAction.setObjectName("donateAction")
        self.exportAction = QtGui.QAction(MainWindow)
        self.exportAction.setIcon(icon11)
        self.exportAction.setObjectName("exportAction")
        self.menu_File.addAction(self.newMessageAction)
        self.menu_File.addAction(self.logAction)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.settingsAction)
        self.menu_File.addAction(self.exportAction)
        self.menu_File.addAction(self.quitAction)
        self.menu_Messages.addAction(self.messageQueueAction)
        self.menu_Messages.addAction(self.historyAction)
        self.menu_Messages.addAction(self.saveMessagesAction)
        self.menu_Messages.addAction(self.statisticsAction)
        self.menu_Messages.addSeparator()
        self.menu_Messages.addAction(self.exportMessagesAction)
        self.menu_Messages.addAction(self.importMessagesAction)
        self.menu_Help.addAction(self.aboutApplicationAction)
        self.menu_Help.addAction(self.aboutQtAction)
        self.menu_Help.addAction(self.donateAction)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Messages.menuAction())
        self.menubar.addAction(self.menu_Contacts.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        self.connectionStack.setCurrentIndex(0)
        self.establishConnectionStack.setCurrentIndex(1)
        self.detailStack.setCurrentIndex(0)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Series60 - Remote", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("MainWindow", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("MainWindow", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("MainWindow", "Calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(4).setText(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(5).setText(QtGui.QApplication.translate("MainWindow", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "No active connection!", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.connectLabel.setText(QtGui.QApplication.translate("MainWindow", "Connection establishment to: <b>unknown</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Connecting...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Updating system informations...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Updating contacts...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Updating calendar entries...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Connected since:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionTimeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Last refresh:", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshTimeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel_2.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Battery level:", None, QtGui.QApplication.UnicodeUTF8))
        self.batteryLabel_2.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Signal strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.signalLabel_2.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectButton.setText(QtGui.QApplication.translate("MainWindow", "Interrupt connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Recipent:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.charLabel.setText(QtGui.QApplication.translate("MainWindow", "160 chars left; 1 message", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsTree.setSortingEnabled(True)
        self.contactsTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Telephone Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsList.setSortingEnabled(True)
        self.contactAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add contact", None, QtGui.QApplication.UnicodeUTF8))
        self.contactEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit contact", None, QtGui.QApplication.UnicodeUTF8))
        self.contactsImportButton.setText(QtGui.QApplication.translate("MainWindow", "Import...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Connected since:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Free drivespace:", None, QtGui.QApplication.UnicodeUTF8))
        self.drivespaceBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Last refresh:", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "IMEI-Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.imeiLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Free RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.freeRamLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Battery level:", None, QtGui.QApplication.UnicodeUTF8))
        self.batteryLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Total RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.totalRamLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Signal strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.signalLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Total ROM:", None, QtGui.QApplication.UnicodeUTF8))
        self.romLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Active profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.profileLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Software version:", None, QtGui.QApplication.UnicodeUTF8))
        self.swLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Bluetooth-address:", None, QtGui.QApplication.UnicodeUTF8))
        self.btAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Application version:", None, QtGui.QApplication.UnicodeUTF8))
        self.programLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Display pixels:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "OS version:", None, QtGui.QApplication.UnicodeUTF8))
        self.osLabel.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Model:", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "IMEI-Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.imeiLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Total RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.totalRamLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Total ROM:", None, QtGui.QApplication.UnicodeUTF8))
        self.romLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Display pixels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "OS version:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.osLabel_3.setText(QtGui.QApplication.translate("MainWindow", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "No active connection!", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Messages.setTitle(QtGui.QApplication.translate("MainWindow", "&Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Contacts.setTitle(QtGui.QApplication.translate("MainWindow", "&Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.newMessageAction.setText(QtGui.QApplication.translate("MainWindow", "&New message", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMessagesAction.setText(QtGui.QApplication.translate("MainWindow", "&Save Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.exportMessagesAction.setText(QtGui.QApplication.translate("MainWindow", "&Export Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.importMessagesAction.setText(QtGui.QApplication.translate("MainWindow", "&Import messages", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsAction.setText(QtGui.QApplication.translate("MainWindow", "&Settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutQtAction.setText(QtGui.QApplication.translate("MainWindow", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.messageQueueAction.setText(QtGui.QApplication.translate("MainWindow", "Message-&Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.historyAction.setText(QtGui.QApplication.translate("MainWindow", "View &history", None, QtGui.QApplication.UnicodeUTF8))
        self.logAction.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutApplicationAction.setText(QtGui.QApplication.translate("MainWindow", "&About Series60-Remote", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticsAction.setText(QtGui.QApplication.translate("MainWindow", "View &statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.donateAction.setText(QtGui.QApplication.translate("MainWindow", "&Donate money...", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAction.setText(QtGui.QApplication.translate("MainWindow", "Export...", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAction.setToolTip(QtGui.QApplication.translate("MainWindow", "Export messages and contacts", None, QtGui.QApplication.UnicodeUTF8))

from widget.CalendarView import CalendarView
from widget.MessageTextEdit import MessageTextEdit
from widget.ObexWidget import ObexWidget
from widget.SearchLineEdit import SearchLineEdit
from widget.DeviceWidget import DeviceDatabaseViewCombobox
import resource_rc
