# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/pixmap_region_selector_dialog.ui'
#
# Created: Wed Nov 17 12:05:58 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PixmapRegionSelectorDialog(object):
    def setupUi(self, PixmapRegionSelectorDialog):
        PixmapRegionSelectorDialog.setObjectName("PixmapRegionSelectorDialog")
        PixmapRegionSelectorDialog.resize(616, 296)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/contacts"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PixmapRegionSelectorDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(PixmapRegionSelectorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(PixmapRegionSelectorDialog)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 95, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pixmapSelectorWidget = PixmapRegionSelectorWidget(PixmapRegionSelectorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmapSelectorWidget.sizePolicy().hasHeightForWidth())
        self.pixmapSelectorWidget.setSizePolicy(sizePolicy)
        self.pixmapSelectorWidget.setObjectName("pixmapSelectorWidget")
        self.verticalLayout.addWidget(self.pixmapSelectorWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_2 = QtGui.QToolButton(PixmapRegionSelectorDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/selection-portrait"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setCheckable(True)
        self.toolButton_2.setChecked(True)
        self.toolButton_2.setAutoExclusive(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton = QtGui.QToolButton(PixmapRegionSelectorDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/selection-landscape"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setCheckable(True)
        self.toolButton.setAutoExclusive(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_3 = QtGui.QToolButton(PixmapRegionSelectorDialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/selection-free-form"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setCheckable(True)
        self.toolButton_3.setAutoExclusive(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        spacerItem1 = QtGui.QSpacerItem(27, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.toolButton_4 = QtGui.QToolButton(PixmapRegionSelectorDialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/object-rotate-right"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout.addWidget(self.toolButton_4)
        self.toolButton_5 = QtGui.QToolButton(PixmapRegionSelectorDialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/object-rotate-left"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout.addWidget(self.toolButton_5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 95, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(PixmapRegionSelectorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PixmapRegionSelectorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PixmapRegionSelectorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PixmapRegionSelectorDialog.reject)
        QtCore.QObject.connect(self.toolButton_4, QtCore.SIGNAL("clicked()"), self.pixmapSelectorWidget.rotateClockwise)
        QtCore.QObject.connect(self.toolButton_5, QtCore.SIGNAL("clicked()"), self.pixmapSelectorWidget.rotateCounterClockwise)
        QtCore.QObject.connect(self.toolButton_3, QtCore.SIGNAL("clicked()"), self.pixmapSelectorWidget.setFreeSelectionAspectRatio)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL("clicked()"), self.pixmapSelectorWidget.setLandscapeFormatSelectionAspectRatio)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL("clicked()"), self.pixmapSelectorWidget.setPortraitFormatSelectionAspectRatio)
        QtCore.QMetaObject.connectSlotsByName(PixmapRegionSelectorDialog)

    def retranslateUi(self, PixmapRegionSelectorDialog):
        PixmapRegionSelectorDialog.setWindowTitle(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Select Region of Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Please click and drag on the image to select the region of interest and rightclick to rotate the image:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Selection in Landscape Format", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setWhatsThis(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Selection in Landscape Format", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Selection in Portrait Format", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setWhatsThis(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Selection in Portrait Format", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setToolTip(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Free selection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setWhatsThis(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Free selection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setToolTip(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Rotate Clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setWhatsThis(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Rotate Clockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setToolTip(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Rotate Counterclockwise", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setWhatsThis(QtGui.QApplication.translate("PixmapRegionSelectorDialog", "Rotate Counterclockwise", None, QtGui.QApplication.UnicodeUTF8))

from widget.PixmapRegionSelectorWidget import PixmapRegionSelectorWidget
import resource_rc
