# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/statistics.ui'
#
# Created: Wed Nov 17 12:05:46 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Statistics(object):
    def setupUi(self, Statistics):
        Statistics.setObjectName("Statistics")
        Statistics.resize(874, 693)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/view-statistics"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Statistics.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Statistics)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statisticTab = QtGui.QTabWidget(Statistics)
        self.statisticTab.setObjectName("statisticTab")
        self.periodTab = QtGui.QWidget()
        self.periodTab.setObjectName("periodTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.periodTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.periodTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.contactBox = QtGui.QComboBox(self.periodTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactBox.sizePolicy().hasHeightForWidth())
        self.contactBox.setSizePolicy(sizePolicy)
        self.contactBox.setObjectName("contactBox")
        self.horizontalLayout_2.addWidget(self.contactBox)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.periodTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.viewBox = QtGui.QComboBox(self.periodTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewBox.sizePolicy().hasHeightForWidth())
        self.viewBox.setSizePolicy(sizePolicy)
        self.viewBox.setObjectName("viewBox")
        self.viewBox.addItem("")
        self.viewBox.addItem("")
        self.viewBox.addItem("")
        self.viewBox.addItem("")
        self.viewBox.addItem("")
        self.viewBox.addItem("")
        self.horizontalLayout_2.addWidget(self.viewBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.periodTab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.filterBox = QtGui.QComboBox(self.periodTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterBox.sizePolicy().hasHeightForWidth())
        self.filterBox.setSizePolicy(sizePolicy)
        self.filterBox.setObjectName("filterBox")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.horizontalLayout_2.addWidget(self.filterBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtGui.QSplitter(self.periodTab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.statisticPlot = StatisticCanvas(self.frame_2)
        self.statisticPlot.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.statisticPlot.setObjectName("statisticPlot")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.statisticPlot)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7.addWidget(self.statisticPlot)
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.infoBrowser = QtGui.QTextBrowser(self.frame)
        self.infoBrowser.setObjectName("infoBrowser")
        self.verticalLayout_5.addWidget(self.infoBrowser)
        self.verticalLayout_2.addWidget(self.splitter)
        self.statisticTab.addTab(self.periodTab, "")
        self.contactTab = QtGui.QWidget()
        self.contactTab.setObjectName("contactTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.contactTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_3 = QtGui.QSplitter(self.contactTab)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_5 = QtGui.QFrame(self.splitter_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.contactPlot = ContactCanvas(self.frame_5)
        self.contactPlot.setObjectName("contactPlot")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.contactPlot)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12.addWidget(self.contactPlot)
        self.frame_6 = QtGui.QFrame(self.splitter_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.contactInfo = QtGui.QTextBrowser(self.frame_6)
        self.contactInfo.setObjectName("contactInfo")
        self.verticalLayout_14.addWidget(self.contactInfo)
        self.verticalLayout_3.addWidget(self.splitter_3)
        self.statisticTab.addTab(self.contactTab, "")
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.generalTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.generalBrowser = QtGui.QTextBrowser(self.generalTab)
        self.generalBrowser.setObjectName("generalBrowser")
        self.verticalLayout_4.addWidget(self.generalBrowser)
        self.statisticTab.addTab(self.generalTab, "")
        self.verticalLayout.addWidget(self.statisticTab)
        self.buttonBox = QtGui.QDialogButtonBox(Statistics)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.stackedAction = QtGui.QAction(Statistics)
        self.stackedAction.setObjectName("stackedAction")
        self.separateAction = QtGui.QAction(Statistics)
        self.separateAction.setObjectName("separateAction")

        self.retranslateUi(Statistics)
        self.statisticTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Statistics.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Statistics.reject)
        QtCore.QMetaObject.connectSlotsByName(Statistics)

    def retranslateUi(self, Statistics):
        Statistics.setWindowTitle(QtGui.QApplication.translate("Statistics", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Statistics", "Contact:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Statistics", "View:", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(0, QtGui.QApplication.translate("Statistics", "Years and Months", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(1, QtGui.QApplication.translate("Statistics", "Years", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(2, QtGui.QApplication.translate("Statistics", "Months", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(3, QtGui.QApplication.translate("Statistics", "Days", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(4, QtGui.QApplication.translate("Statistics", "Weekdays", None, QtGui.QApplication.UnicodeUTF8))
        self.viewBox.setItemText(5, QtGui.QApplication.translate("Statistics", "Hours", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Statistics", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(0, QtGui.QApplication.translate("Statistics", "All messages", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(1, QtGui.QApplication.translate("Statistics", "Only incoming", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBox.setItemText(2, QtGui.QApplication.translate("Statistics", "Only outgoing", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticPlot.setToolTip(QtGui.QApplication.translate("Statistics", "Rightclick to change layout", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticTab.setTabText(self.statisticTab.indexOf(self.periodTab), QtGui.QApplication.translate("Statistics", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticTab.setTabText(self.statisticTab.indexOf(self.contactTab), QtGui.QApplication.translate("Statistics", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.statisticTab.setTabText(self.statisticTab.indexOf(self.generalTab), QtGui.QApplication.translate("Statistics", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.stackedAction.setText(QtGui.QApplication.translate("Statistics", "Show graphs on top of each other", None, QtGui.QApplication.UnicodeUTF8))
        self.separateAction.setText(QtGui.QApplication.translate("Statistics", "Show one graph above the x-axis and the other under the x-axis", None, QtGui.QApplication.UnicodeUTF8))

from widget.StatisticCanvas import StatisticCanvas
from widget.ContactCanvas import ContactCanvas
import resource_rc
