# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/settings.ui'
#
# Created: Wed Nov 17 12:06:04 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(802, 599)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/configure"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        self.verticalLayout_24 = QtGui.QVBoxLayout(Settings)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.mobileTab = QtGui.QWidget()
        self.mobileTab.setObjectName("mobileTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.mobileTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.mobileTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.selectedDevicesList = DeviceViewWidget(self.groupBox)
        self.selectedDevicesList.setObjectName("selectedDevicesList")
        self.verticalLayout.addWidget(self.selectedDevicesList)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addDeviceButton = QtGui.QPushButton(self.groupBox)
        self.addDeviceButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/go-previous"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addDeviceButton.setIcon(icon1)
        self.addDeviceButton.setObjectName("addDeviceButton")
        self.verticalLayout_3.addWidget(self.addDeviceButton)
        self.removeDeviceButton = QtGui.QPushButton(self.groupBox)
        self.removeDeviceButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/go-next"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeDeviceButton.setIcon(icon2)
        self.removeDeviceButton.setObjectName("removeDeviceButton")
        self.verticalLayout_3.addWidget(self.removeDeviceButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.allDevicesList = DeviceScanWidget(self.groupBox)
        self.allDevicesList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.allDevicesList.setObjectName("allDevicesList")
        self.verticalLayout_2.addWidget(self.allDevicesList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.mobileTab, "")
        self.applicationTab = QtGui.QWidget()
        self.applicationTab.setObjectName("applicationTab")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.applicationTab)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.groupBox_5 = QtGui.QGroupBox(self.applicationTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setContentsMargins(15, -1, -1, 10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.markAsReadBox = QtGui.QCheckBox(self.groupBox_5)
        self.markAsReadBox.setObjectName("markAsReadBox")
        self.verticalLayout_9.addWidget(self.markAsReadBox)
        self.quitOnCloseBox = QtGui.QCheckBox(self.groupBox_5)
        self.quitOnCloseBox.setObjectName("quitOnCloseBox")
        self.verticalLayout_9.addWidget(self.quitOnCloseBox)
        self.saveMessagesBox = QtGui.QCheckBox(self.groupBox_5)
        self.saveMessagesBox.setObjectName("saveMessagesBox")
        self.verticalLayout_9.addWidget(self.saveMessagesBox)
        self.verticalLayout_26.addWidget(self.groupBox_5)
        self.groupBox_4 = QtGui.QGroupBox(self.applicationTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setContentsMargins(15, -1, -1, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.showCellnumberBox = QtGui.QCheckBox(self.groupBox_4)
        self.showCellnumberBox.setObjectName("showCellnumberBox")
        self.verticalLayout_6.addWidget(self.showCellnumberBox)
        self.sendMessageOnReturnBox = QtGui.QCheckBox(self.groupBox_4)
        self.sendMessageOnReturnBox.setObjectName("sendMessageOnReturnBox")
        self.verticalLayout_6.addWidget(self.sendMessageOnReturnBox)
        self.verticalLayout_26.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.applicationTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setContentsMargins(15, -1, -1, 10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.showPopupBox = QtGui.QCheckBox(self.groupBox_6)
        self.showPopupBox.setObjectName("showPopupBox")
        self.verticalLayout_10.addWidget(self.showPopupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.popupLabel_1 = QtGui.QLabel(self.groupBox_6)
        self.popupLabel_1.setEnabled(False)
        self.popupLabel_1.setObjectName("popupLabel_1")
        self.horizontalLayout_3.addWidget(self.popupLabel_1)
        self.timeoutPopupBox = QtGui.QSpinBox(self.groupBox_6)
        self.timeoutPopupBox.setEnabled(False)
        self.timeoutPopupBox.setMaximum(999)
        self.timeoutPopupBox.setObjectName("timeoutPopupBox")
        self.horizontalLayout_3.addWidget(self.timeoutPopupBox)
        self.popupLabel_2 = QtGui.QLabel(self.groupBox_6)
        self.popupLabel_2.setEnabled(False)
        self.popupLabel_2.setObjectName("popupLabel_2")
        self.horizontalLayout_3.addWidget(self.popupLabel_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.animatePopupBox = QtGui.QCheckBox(self.groupBox_6)
        self.animatePopupBox.setObjectName("animatePopupBox")
        self.verticalLayout_10.addWidget(self.animatePopupBox)
        self.verticalLayout_26.addWidget(self.groupBox_6)
        self.groupBox_11 = QtGui.QGroupBox(self.applicationTab)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_11.setContentsMargins(15, -1, -1, 20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.autoConnectBox = QtGui.QCheckBox(self.groupBox_11)
        self.autoConnectBox.setObjectName("autoConnectBox")
        self.verticalLayout_11.addWidget(self.autoConnectBox)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.popupLabel_3 = QtGui.QLabel(self.groupBox_11)
        self.popupLabel_3.setEnabled(False)
        self.popupLabel_3.setObjectName("popupLabel_3")
        self.horizontalLayout_11.addWidget(self.popupLabel_3)
        self.autoConnectIntervalBox = QtGui.QSpinBox(self.groupBox_11)
        self.autoConnectIntervalBox.setEnabled(False)
        self.autoConnectIntervalBox.setMinimum(30)
        self.autoConnectIntervalBox.setMaximum(1200)
        self.autoConnectIntervalBox.setObjectName("autoConnectIntervalBox")
        self.horizontalLayout_11.addWidget(self.autoConnectIntervalBox)
        self.popupLabel_4 = QtGui.QLabel(self.groupBox_11)
        self.popupLabel_4.setEnabled(False)
        self.popupLabel_4.setObjectName("popupLabel_4")
        self.horizontalLayout_11.addWidget(self.popupLabel_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.autoStartBox = QtGui.QCheckBox(self.groupBox_11)
        self.autoStartBox.setObjectName("autoStartBox")
        self.verticalLayout_11.addWidget(self.autoStartBox)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.autoStartMinimizedBox = QtGui.QCheckBox(self.groupBox_11)
        self.autoStartMinimizedBox.setEnabled(False)
        self.autoStartMinimizedBox.setObjectName("autoStartMinimizedBox")
        self.horizontalLayout_12.addWidget(self.autoStartMinimizedBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_26.addWidget(self.groupBox_11)
        self.tabWidget.addTab(self.applicationTab, "")
        self.contactsTab = QtGui.QWidget()
        self.contactsTab.setObjectName("contactsTab")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.contactsTab)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_8 = QtGui.QGroupBox(self.contactsTab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setContentsMargins(15, -1, -1, 15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ignoreAllContactsBox = QtGui.QCheckBox(self.groupBox_8)
        self.ignoreAllContactsBox.setObjectName("ignoreAllContactsBox")
        self.verticalLayout_15.addWidget(self.ignoreAllContactsBox)
        self.displayIconBox = QtGui.QCheckBox(self.groupBox_8)
        self.displayIconBox.setObjectName("displayIconBox")
        self.verticalLayout_15.addWidget(self.displayIconBox)
        self.verticalLayout_16.addWidget(self.groupBox_8)
        self.groupBox_7 = QtGui.QGroupBox(self.contactsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.blockedContactsList = QtGui.QListWidget(self.groupBox_7)
        self.blockedContactsList.setObjectName("blockedContactsList")
        self.verticalLayout_12.addWidget(self.blockedContactsList)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.addContactButton = QtGui.QPushButton(self.groupBox_7)
        self.addContactButton.setText("")
        self.addContactButton.setIcon(icon1)
        self.addContactButton.setObjectName("addContactButton")
        self.verticalLayout_13.addWidget(self.addContactButton)
        self.removeContactButton = QtGui.QPushButton(self.groupBox_7)
        self.removeContactButton.setText("")
        self.removeContactButton.setIcon(icon2)
        self.removeContactButton.setObjectName("removeContactButton")
        self.verticalLayout_13.addWidget(self.removeContactButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.allContactsList = QtGui.QListWidget(self.groupBox_7)
        self.allContactsList.setObjectName("allContactsList")
        self.verticalLayout_14.addWidget(self.allContactsList)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.contactsTab, "")
        self.chatTab = QtGui.QWidget()
        self.chatTab.setObjectName("chatTab")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.chatTab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self._4 = QtGui.QGridLayout()
        self._4.setMargin(0)
        self._4.setSpacing(6)
        self._4.setObjectName("_4")
        self.groupBox_9 = QtGui.QGroupBox(self.chatTab)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupMessagesBox = QtGui.QCheckBox(self.groupBox_9)
        self.groupMessagesBox.setObjectName("groupMessagesBox")
        self.horizontalLayout_4.addWidget(self.groupMessagesBox)
        self.compactBox = QtGui.QCheckBox(self.groupBox_9)
        self.compactBox.setObjectName("compactBox")
        self.horizontalLayout_4.addWidget(self.compactBox)
        self.verticalLayout_22.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtGui.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.lastMessagesBox = QtGui.QSpinBox(self.groupBox_9)
        self.lastMessagesBox.setMaximum(20)
        self.lastMessagesBox.setObjectName("lastMessagesBox")
        self.horizontalLayout_5.addWidget(self.lastMessagesBox)
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_22.addLayout(self.horizontalLayout_5)
        self._4.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.themesGroupBox_2 = QtGui.QGroupBox(self.chatTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themesGroupBox_2.sizePolicy().hasHeightForWidth())
        self.themesGroupBox_2.setSizePolicy(sizePolicy)
        self.themesGroupBox_2.setObjectName("themesGroupBox_2")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.themesGroupBox_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.splitter = QtGui.QSplitter(self.themesGroupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.themeList = QtGui.QListWidget(self.splitter)
        self.themeList.setObjectName("themeList")
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.messagesView = ChatMessageView(self.frame)
        self.messagesView.setObjectName("messagesView")
        self.verticalLayout_19.addWidget(self.messagesView)
        self.verticalLayout_20.addWidget(self.splitter)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textLabel1_2 = QtGui.QLabel(self.themesGroupBox_2)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.horizontalLayout_10.addWidget(self.textLabel1_2)
        self.themeVariantsList = QtGui.QComboBox(self.themesGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeVariantsList.sizePolicy().hasHeightForWidth())
        self.themeVariantsList.setSizePolicy(sizePolicy)
        self.themeVariantsList.setObjectName("themeVariantsList")
        self.horizontalLayout_10.addWidget(self.themeVariantsList)
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.installThemeButton = QtGui.QPushButton(self.themesGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installThemeButton.sizePolicy().hasHeightForWidth())
        self.installThemeButton.setSizePolicy(sizePolicy)
        self.installThemeButton.setObjectName("installThemeButton")
        self.horizontalLayout_10.addWidget(self.installThemeButton)
        self.deleteThemeButton = QtGui.QPushButton(self.themesGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteThemeButton.sizePolicy().hasHeightForWidth())
        self.deleteThemeButton.setSizePolicy(sizePolicy)
        self.deleteThemeButton.setObjectName("deleteThemeButton")
        self.horizontalLayout_10.addWidget(self.deleteThemeButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_10)
        self._4.addWidget(self.themesGroupBox_2, 0, 0, 1, 1)
        self.verticalLayout_21.addLayout(self._4)
        self.tabWidget.addTab(self.chatTab, "")
        self.databaseTab = QtGui.QWidget()
        self.databaseTab.setObjectName("databaseTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.databaseTab)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setContentsMargins(-1, 10, -1, 20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, 15, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.databaseTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.typeBox = QtGui.QComboBox(self.databaseTab)
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.typeBox.setItemText(0, "SQLite")
        self.typeBox.addItem("")
        self.typeBox.setItemText(1, "MySQL")
        self.horizontalLayout.addWidget(self.typeBox)
        spacerItem4 = QtGui.QSpacerItem(378, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.stackedWidget = QtGui.QStackedWidget(self.databaseTab)
        self.stackedWidget.setObjectName("stackedWidget")
        self.sqlitePage = QtGui.QWidget()
        self.sqlitePage.setObjectName("sqlitePage")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.sqlitePage)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setContentsMargins(15, 15, 15, 20)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.sqliteDriverNotFoundLabel = QtGui.QLabel(self.sqlitePage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sqliteDriverNotFoundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sqliteDriverNotFoundLabel.setFont(font)
        self.sqliteDriverNotFoundLabel.setTextFormat(QtCore.Qt.RichText)
        self.sqliteDriverNotFoundLabel.setWordWrap(True)
        self.sqliteDriverNotFoundLabel.setObjectName("sqliteDriverNotFoundLabel")
        self.verticalLayout_17.addWidget(self.sqliteDriverNotFoundLabel)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.sqlitePage)
        self.mysqlPage = QtGui.QWidget()
        self.mysqlPage.setObjectName("mysqlPage")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.mysqlPage)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setContentsMargins(15, 15, 15, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mysqlDriverNotFoundLabel = QtGui.QLabel(self.mysqlPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.mysqlDriverNotFoundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.mysqlDriverNotFoundLabel.setFont(font)
        self.mysqlDriverNotFoundLabel.setTextFormat(QtCore.Qt.RichText)
        self.mysqlDriverNotFoundLabel.setWordWrap(True)
        self.mysqlDriverNotFoundLabel.setObjectName("mysqlDriverNotFoundLabel")
        self.verticalLayout_8.addWidget(self.mysqlDriverNotFoundLabel)
        self.mysqlSettingsBox = QtGui.QGroupBox(self.mysqlPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysqlSettingsBox.sizePolicy().hasHeightForWidth())
        self.mysqlSettingsBox.setSizePolicy(sizePolicy)
        self.mysqlSettingsBox.setObjectName("mysqlSettingsBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.mysqlSettingsBox)
        self.gridLayout_3.setContentsMargins(15, -1, 15, 15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.mysql_hostLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_hostLine.setText("localhost")
        self.mysql_hostLine.setObjectName("mysql_hostLine")
        self.gridLayout_3.addWidget(self.mysql_hostLine, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 2, 3, 1)
        self.label_7 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)
        self.mysql_portBox = QtGui.QSpinBox(self.mysqlSettingsBox)
        self.mysql_portBox.setMaximum(65535)
        self.mysql_portBox.setProperty("value", 3306)
        self.mysql_portBox.setObjectName("mysql_portBox")
        self.gridLayout_3.addWidget(self.mysql_portBox, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.mysql_userLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_userLine.setObjectName("mysql_userLine")
        self.gridLayout_3.addWidget(self.mysql_userLine, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 3, 1, 1)
        self.mysql_passLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_passLine.setEchoMode(QtGui.QLineEdit.Password)
        self.mysql_passLine.setObjectName("mysql_passLine")
        self.gridLayout_3.addWidget(self.mysql_passLine, 2, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.mysql_databaseLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_databaseLine.setObjectName("mysql_databaseLine")
        self.gridLayout_3.addWidget(self.mysql_databaseLine, 3, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.mysqlSettingsBox)
        self.stackedWidget.addWidget(self.mysqlPage)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        spacerItem7 = QtGui.QSpacerItem(20, 58, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.tabWidget.addTab(self.databaseTab, "")
        self.advancedTab = QtGui.QWidget()
        self.advancedTab.setObjectName("advancedTab")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.advancedTab)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_2 = QtGui.QGroupBox(self.advancedTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setContentsMargins(15, -1, -1, 20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.pluginBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pluginBox.sizePolicy().hasHeightForWidth())
        self.pluginBox.setSizePolicy(sizePolicy)
        self.pluginBox.setObjectName("pluginBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pluginBox)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.portBox = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portBox.sizePolicy().hasHeightForWidth())
        self.portBox.setSizePolicy(sizePolicy)
        self.portBox.setObjectName("portBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.portBox)
        self.horizontalLayout_7.addLayout(self.formLayout_2)
        spacerItem8 = QtGui.QSpacerItem(328, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_18.addWidget(self.groupBox_2)
        self.groupBox_10 = QtGui.QGroupBox(self.advancedTab)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_25.setSpacing(10)
        self.verticalLayout_25.setContentsMargins(15, -1, -1, 20)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.updateIntervalLabel = QtGui.QLabel(self.groupBox_10)
        self.updateIntervalLabel.setObjectName("updateIntervalLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.updateIntervalLabel)
        self.updateIntervalBox = QtGui.QComboBox(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateIntervalBox.sizePolicy().hasHeightForWidth())
        self.updateIntervalBox.setSizePolicy(sizePolicy)
        self.updateIntervalBox.setObjectName("updateIntervalBox")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.updateIntervalBox)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.updateUnstableBox = QtGui.QCheckBox(self.groupBox_10)
        self.updateUnstableBox.setObjectName("updateUnstableBox")
        self.verticalLayout_5.addWidget(self.updateUnstableBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_25.addLayout(self.horizontalLayout_9)
        self.verticalLayout_18.addWidget(self.groupBox_10)
        self.groupBox_3 = QtGui.QGroupBox(self.advancedTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_23.setSpacing(10)
        self.verticalLayout_23.setContentsMargins(15, -1, -1, 20)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.widgetStyleBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetStyleBox.sizePolicy().hasHeightForWidth())
        self.widgetStyleBox.setSizePolicy(sizePolicy)
        self.widgetStyleBox.setObjectName("widgetStyleBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.widgetStyleBox)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.languageBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageBox.sizePolicy().hasHeightForWidth())
        self.languageBox.setSizePolicy(sizePolicy)
        self.languageBox.setObjectName("languageBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.languageBox)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.countryBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countryBox.sizePolicy().hasHeightForWidth())
        self.countryBox.setSizePolicy(sizePolicy)
        self.countryBox.setObjectName("countryBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.countryBox)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.chatGroupBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatGroupBox.sizePolicy().hasHeightForWidth())
        self.chatGroupBox.setSizePolicy(sizePolicy)
        self.chatGroupBox.setObjectName("chatGroupBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.chatGroupBox)
        self.horizontalLayout_8.addLayout(self.formLayout)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_23.addLayout(self.horizontalLayout_8)
        self.restartHintLabel = QtGui.QLabel(self.groupBox_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.restartHintLabel.setPalette(palette)
        self.restartHintLabel.setObjectName("restartHintLabel")
        self.verticalLayout_23.addWidget(self.restartHintLabel)
        self.verticalLayout_18.addWidget(self.groupBox_3)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem11)
        self.tabWidget.addTab(self.advancedTab, "")
        self.verticalLayout_24.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_24.addWidget(self.buttonBox)
        self.label_5.setBuddy(self.typeBox)
        self.label_6.setBuddy(self.mysql_hostLine)
        self.label_7.setBuddy(self.mysql_portBox)
        self.label_8.setBuddy(self.mysql_userLine)
        self.label_9.setBuddy(self.mysql_passLine)
        self.label_10.setBuddy(self.mysql_databaseLine)
        self.label.setBuddy(self.pluginBox)
        self.label_2.setBuddy(self.portBox)
        self.updateIntervalLabel.setBuddy(self.updateIntervalBox)
        self.label_16.setBuddy(self.widgetStyleBox)
        self.label_17.setBuddy(self.languageBox)
        self.label_15.setBuddy(self.countryBox)
        self.label_18.setBuddy(self.chatGroupBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Settings.reject)
        QtCore.QObject.connect(self.typeBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.showPopupBox, QtCore.SIGNAL("toggled(bool)"), self.timeoutPopupBox.setEnabled)
        QtCore.QObject.connect(self.showPopupBox, QtCore.SIGNAL("toggled(bool)"), self.popupLabel_1.setEnabled)
        QtCore.QObject.connect(self.showPopupBox, QtCore.SIGNAL("toggled(bool)"), self.popupLabel_2.setEnabled)
        QtCore.QObject.connect(self.widgetStyleBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.restartHintLabel.show)
        QtCore.QObject.connect(self.languageBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.restartHintLabel.show)
        QtCore.QObject.connect(self.countryBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.restartHintLabel.show)
        QtCore.QObject.connect(self.autoConnectBox, QtCore.SIGNAL("toggled(bool)"), self.popupLabel_3.setEnabled)
        QtCore.QObject.connect(self.autoConnectBox, QtCore.SIGNAL("toggled(bool)"), self.autoConnectIntervalBox.setEnabled)
        QtCore.QObject.connect(self.autoConnectBox, QtCore.SIGNAL("toggled(bool)"), self.popupLabel_4.setEnabled)
        QtCore.QObject.connect(self.autoStartBox, QtCore.SIGNAL("toggled(bool)"), self.autoStartMinimizedBox.setEnabled)
        QtCore.QObject.connect(self.chatGroupBox, QtCore.SIGNAL("currentIndexChanged(int)"), self.restartHintLabel.show)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.tabWidget, self.selectedDevicesList)
        Settings.setTabOrder(self.selectedDevicesList, self.allDevicesList)
        Settings.setTabOrder(self.allDevicesList, self.addDeviceButton)
        Settings.setTabOrder(self.addDeviceButton, self.removeDeviceButton)
        Settings.setTabOrder(self.removeDeviceButton, self.buttonBox)
        Settings.setTabOrder(self.buttonBox, self.markAsReadBox)
        Settings.setTabOrder(self.markAsReadBox, self.quitOnCloseBox)
        Settings.setTabOrder(self.quitOnCloseBox, self.saveMessagesBox)
        Settings.setTabOrder(self.saveMessagesBox, self.showCellnumberBox)
        Settings.setTabOrder(self.showCellnumberBox, self.sendMessageOnReturnBox)
        Settings.setTabOrder(self.sendMessageOnReturnBox, self.showPopupBox)
        Settings.setTabOrder(self.showPopupBox, self.timeoutPopupBox)
        Settings.setTabOrder(self.timeoutPopupBox, self.animatePopupBox)
        Settings.setTabOrder(self.animatePopupBox, self.autoConnectBox)
        Settings.setTabOrder(self.autoConnectBox, self.autoConnectIntervalBox)
        Settings.setTabOrder(self.autoConnectIntervalBox, self.autoStartBox)
        Settings.setTabOrder(self.autoStartBox, self.autoStartMinimizedBox)
        Settings.setTabOrder(self.autoStartMinimizedBox, self.ignoreAllContactsBox)
        Settings.setTabOrder(self.ignoreAllContactsBox, self.displayIconBox)
        Settings.setTabOrder(self.displayIconBox, self.blockedContactsList)
        Settings.setTabOrder(self.blockedContactsList, self.allContactsList)
        Settings.setTabOrder(self.allContactsList, self.addContactButton)
        Settings.setTabOrder(self.addContactButton, self.removeContactButton)
        Settings.setTabOrder(self.removeContactButton, self.themeList)
        Settings.setTabOrder(self.themeList, self.messagesView)
        Settings.setTabOrder(self.messagesView, self.themeVariantsList)
        Settings.setTabOrder(self.themeVariantsList, self.installThemeButton)
        Settings.setTabOrder(self.installThemeButton, self.deleteThemeButton)
        Settings.setTabOrder(self.deleteThemeButton, self.groupMessagesBox)
        Settings.setTabOrder(self.groupMessagesBox, self.lastMessagesBox)
        Settings.setTabOrder(self.lastMessagesBox, self.compactBox)
        Settings.setTabOrder(self.compactBox, self.typeBox)
        Settings.setTabOrder(self.typeBox, self.mysql_hostLine)
        Settings.setTabOrder(self.mysql_hostLine, self.mysql_portBox)
        Settings.setTabOrder(self.mysql_portBox, self.mysql_userLine)
        Settings.setTabOrder(self.mysql_userLine, self.mysql_passLine)
        Settings.setTabOrder(self.mysql_passLine, self.mysql_databaseLine)
        Settings.setTabOrder(self.mysql_databaseLine, self.pluginBox)
        Settings.setTabOrder(self.pluginBox, self.portBox)
        Settings.setTabOrder(self.portBox, self.updateIntervalBox)
        Settings.setTabOrder(self.updateIntervalBox, self.updateUnstableBox)
        Settings.setTabOrder(self.updateUnstableBox, self.chatGroupBox)
        Settings.setTabOrder(self.chatGroupBox, self.widgetStyleBox)
        Settings.setTabOrder(self.widgetStyleBox, self.languageBox)
        Settings.setTabOrder(self.languageBox, self.countryBox)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Settings", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "Selected devices:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Settings", "Available devices:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mobileTab), QtGui.QApplication.translate("Settings", "Mobile", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.markAsReadBox.setText(QtGui.QApplication.translate("Settings", "Mark messages as read on the device", None, QtGui.QApplication.UnicodeUTF8))
        self.quitOnCloseBox.setText(QtGui.QApplication.translate("Settings", "Quit the application when closing the mainwindow", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMessagesBox.setText(QtGui.QApplication.translate("Settings", "Store messages on the PC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Settings", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.showCellnumberBox.setText(QtGui.QApplication.translate("Settings", "Show telephone number in the contact list by the messages", None, QtGui.QApplication.UnicodeUTF8))
        self.sendMessageOnReturnBox.setText(QtGui.QApplication.translate("Settings", "Send message when the Return key is pressed (Ctrl+Return or Enter for Newline)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Settings", "Popups", None, QtGui.QApplication.UnicodeUTF8))
        self.showPopupBox.setText(QtGui.QApplication.translate("Settings", "Show popups", None, QtGui.QApplication.UnicodeUTF8))
        self.popupLabel_1.setText(QtGui.QApplication.translate("Settings", "Close the popup after", None, QtGui.QApplication.UnicodeUTF8))
        self.popupLabel_2.setText(QtGui.QApplication.translate("Settings", "seconds (0 is never)", None, QtGui.QApplication.UnicodeUTF8))
        self.animatePopupBox.setText(QtGui.QApplication.translate("Settings", "Animate popups", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("Settings", "Autoconnect && Autostart", None, QtGui.QApplication.UnicodeUTF8))
        self.autoConnectBox.setText(QtGui.QApplication.translate("Settings", "Automatically connect to devices", None, QtGui.QApplication.UnicodeUTF8))
        self.popupLabel_3.setText(QtGui.QApplication.translate("Settings", "Scan interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.popupLabel_4.setText(QtGui.QApplication.translate("Settings", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.autoStartBox.setText(QtGui.QApplication.translate("Settings", "Autostart Series60-Remote on system startup", None, QtGui.QApplication.UnicodeUTF8))
        self.autoStartMinimizedBox.setText(QtGui.QApplication.translate("Settings", "Start minimized in the system tray", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.applicationTab), QtGui.QApplication.translate("Settings", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoreAllContactsBox.setText(QtGui.QApplication.translate("Settings", "Block all contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.displayIconBox.setText(QtGui.QApplication.translate("Settings", "Show contact icon in the list", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Settings", "Blocked contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Settings", "Blocked contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Settings", "Available contacts:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contactsTab), QtGui.QApplication.translate("Settings", "Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Settings", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.groupMessagesBox.setText(QtGui.QApplication.translate("Settings", "Group consecuti&ve messages", None, QtGui.QApplication.UnicodeUTF8))
        self.compactBox.setText(QtGui.QApplication.translate("Settings", "Use compact variant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Settings", "Show the last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Settings", "messages", None, QtGui.QApplication.UnicodeUTF8))
        self.themesGroupBox_2.setTitle(QtGui.QApplication.translate("Settings", "Themes", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("Settings", "Theme variant:", None, QtGui.QApplication.UnicodeUTF8))
        self.installThemeButton.setText(QtGui.QApplication.translate("Settings", "&Install Theme...", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteThemeButton.setText(QtGui.QApplication.translate("Settings", "&Delete Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chatTab), QtGui.QApplication.translate("Settings", "Chat - Themes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "Database type:", None, QtGui.QApplication.UnicodeUTF8))
        self.sqliteDriverNotFoundLabel.setText(QtGui.QApplication.translate("Settings", "Warning! <i>QSQLITE</i> database driver not found! Please install it first!", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlDriverNotFoundLabel.setText(QtGui.QApplication.translate("Settings", "Warning! <i>QMYSQL</i> database driver not found! Please install it first!", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlSettingsBox.setTitle(QtGui.QApplication.translate("Settings", "Configure MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Settings", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Settings", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Settings", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Settings", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.databaseTab), QtGui.QApplication.translate("Settings", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Settings", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "Plugin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Settings", "Update checker", None, QtGui.QApplication.UnicodeUTF8))
        self.updateIntervalLabel.setText(QtGui.QApplication.translate("Settings", "Update check interval: ", None, QtGui.QApplication.UnicodeUTF8))
        self.updateUnstableBox.setText(QtGui.QApplication.translate("Settings", "Show also updates to unstable versions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Settings", "Look && Feel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Settings", "Widget style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Settings", "Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Settings", "Country:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Settings", "Chat window grouping:", None, QtGui.QApplication.UnicodeUTF8))
        self.restartHintLabel.setText(QtGui.QApplication.translate("Settings", "Note: You need to restart the application that these changes take effect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advancedTab), QtGui.QApplication.translate("Settings", "Advanced Options", None, QtGui.QApplication.UnicodeUTF8))

from widget.ChatMessageView import ChatMessageView
from widget.DeviceWidget import DeviceViewWidget, DeviceScanWidget
import resource_rc
