# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/wizard_databasePage.ui'
#
# Created: Wed Nov 17 12:05:55 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_databasePage(object):
    def setupUi(self, databasePage):
        databasePage.setObjectName("databasePage")
        databasePage.resize(590, 380)
        databasePage.setMinimumSize(QtCore.QSize(590, 380))
        self.verticalLayout = QtGui.QVBoxLayout(databasePage)
        self.verticalLayout.setContentsMargins(10, 10, 10, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(databasePage)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(databasePage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.typeBox = QtGui.QComboBox(databasePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeBox.sizePolicy().hasHeightForWidth())
        self.typeBox.setSizePolicy(sizePolicy)
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.typeBox.setItemText(0, "SQLite")
        self.typeBox.addItem("")
        self.typeBox.setItemText(1, "MySQL")
        self.horizontalLayout.addWidget(self.typeBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(348, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(databasePage)
        self.stackedWidget.setObjectName("stackedWidget")
        self.sqlitePage = QtGui.QWidget()
        self.sqlitePage.setObjectName("sqlitePage")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.sqlitePage)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.sqliteDriverNotFoundLabel = QtGui.QLabel(self.sqlitePage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.sqliteDriverNotFoundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sqliteDriverNotFoundLabel.setFont(font)
        self.sqliteDriverNotFoundLabel.setTextFormat(QtCore.Qt.RichText)
        self.sqliteDriverNotFoundLabel.setWordWrap(True)
        self.sqliteDriverNotFoundLabel.setObjectName("sqliteDriverNotFoundLabel")
        self.verticalLayout_17.addWidget(self.sqliteDriverNotFoundLabel)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.sqlitePage)
        self.mysqlPage = QtGui.QWidget()
        self.mysqlPage.setObjectName("mysqlPage")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.mysqlPage)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setContentsMargins(10, 20, 10, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mysqlDriverNotFoundLabel = QtGui.QLabel(self.mysqlPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.mysqlDriverNotFoundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.mysqlDriverNotFoundLabel.setFont(font)
        self.mysqlDriverNotFoundLabel.setTextFormat(QtCore.Qt.RichText)
        self.mysqlDriverNotFoundLabel.setWordWrap(True)
        self.mysqlDriverNotFoundLabel.setObjectName("mysqlDriverNotFoundLabel")
        self.verticalLayout_8.addWidget(self.mysqlDriverNotFoundLabel)
        self.mysqlSettingsBox = QtGui.QGroupBox(self.mysqlPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mysqlSettingsBox.sizePolicy().hasHeightForWidth())
        self.mysqlSettingsBox.setSizePolicy(sizePolicy)
        self.mysqlSettingsBox.setObjectName("mysqlSettingsBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.mysqlSettingsBox)
        self.gridLayout_3.setContentsMargins(15, -1, 15, 15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.mysql_hostLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_hostLine.setText("localhost")
        self.mysql_hostLine.setObjectName("mysql_hostLine")
        self.gridLayout_3.addWidget(self.mysql_hostLine, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 2, 3, 1)
        self.label_7 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)
        self.mysql_portBox = QtGui.QSpinBox(self.mysqlSettingsBox)
        self.mysql_portBox.setMaximum(65535)
        self.mysql_portBox.setProperty("value", 3306)
        self.mysql_portBox.setObjectName("mysql_portBox")
        self.gridLayout_3.addWidget(self.mysql_portBox, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.mysql_userLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_userLine.setObjectName("mysql_userLine")
        self.gridLayout_3.addWidget(self.mysql_userLine, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 3, 1, 1)
        self.mysql_passLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_passLine.setEchoMode(QtGui.QLineEdit.Password)
        self.mysql_passLine.setObjectName("mysql_passLine")
        self.gridLayout_3.addWidget(self.mysql_passLine, 2, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.mysqlSettingsBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.mysql_databaseLine = QtGui.QLineEdit(self.mysqlSettingsBox)
        self.mysql_databaseLine.setObjectName("mysql_databaseLine")
        self.gridLayout_3.addWidget(self.mysql_databaseLine, 3, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.mysqlSettingsBox)
        self.stackedWidget.addWidget(self.mysqlPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(databasePage)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.typeBox, QtCore.SIGNAL("activated(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(databasePage)

    def retranslateUi(self, databasePage):
        self.label.setText(QtGui.QApplication.translate("databasePage", "Please select your database type (If you are unsure use SQLite):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("databasePage", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.sqliteDriverNotFoundLabel.setText(QtGui.QApplication.translate("databasePage", "Warning! <i>QSQLITE</i> database driver not found! Please install it first!", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlDriverNotFoundLabel.setText(QtGui.QApplication.translate("databasePage", "Warning! <i>QMYSQL</i> database driver not found! Please install it first!", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlSettingsBox.setTitle(QtGui.QApplication.translate("databasePage", "Configure MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("databasePage", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("databasePage", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("databasePage", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("databasePage", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("databasePage", "Database:", None, QtGui.QApplication.UnicodeUTF8))

